[Dion] Step3 완료했습니다.
code-squad/java-qna pull request #162
Opened 2020-02-25 12:53 UTC by ksundong

# 기능 구현

1. 세션을 이용한 로그인 구현
2. 로그인 상태에 따른 화면 처리 및 기능 구현
3. 로그아웃 기능 구현 ⇒  `GET` method를 사용하였는데, `POST`를 사용하는게 더 좋다는 얘기를 들었습니다.
   네이버는 `GET`으로 구현되어 있지만 github이나 stackoverflow의 경우는 `POST`로 구현되어있었습니다.
4. 테스트 데이터를 적극 활용하고자 하였습니다. 이렇게 하는게 맞는지는 모르겠습니다...
5. 개인 정보 수정이 본인만 가능하도록 하였습니다.
6. 게시물 작성, 수정, 삭제 기능을 로그인 기능과 적절히 연동하고자 하였습니다.
7. 댓글 기능도 마찬가지로 로그인 기능과 적절히 연동하고자 하였습니다. (어렵네요.)

세션을 이용하면서 코드를 간추리고자 하였는데, 잘 안되네요.
일단 리뷰를 받고 수정을 더 하는 쪽으로 생각하고 있습니다.

감사합니다. 👍

2020-02-27 14:31 UTC, ksundong commented
@honux77 

> 저도 몰랐는데 로그인에 POST를 많이 사용하네요. POST 좋은 것 같아요.

로그인 말고 로그아웃 말씀하신거 맞으시죠..?
해당 내용은 Solar가 얘기해주셔서 알게되었습니다.

2020-02-28 00:11 UTC, wheejuni requested changes
수고 많으셨습니다. 
리뷰가 늦어져 죄송합니다. ㅠ 아래 수정사항 코멘트 남겨드리니 확인해주세요.

2020-02-28 00:11 UTC, wheejuni commented on src/main/java/com/codessquad/qna/user/UserController.java
>          model.addAttribute("httpMethod", "POST");
요청을 주고받을 메소드의 결정은 프론트엔드의 코드가 전담하게 합시다. 
API는 늘 변경되기 마련인데, 지금이야 handlebars 기반으로 프론트 뷰를 그리고 있으니 상관없지만,
나중에 React 와 같은 SPA로 전환한다 치면, 지금 이렇게 컨트롤러 메소드 곳곳에 산재되어 있는 method 결정 로직을 어떻게 다 옮길 수 있을지 생각해봐야 할 겁니다.

2020-02-28 00:11 UTC, wheejuni commented on src/main/java/com/codessquad/qna/user/UserController.java
> +    }
`User` 의 `.equals()` 로 부족하다면 해당 클래스에 다른 메소드를 작성하는 게 맞습니다.
컨트롤러가 가질 private method는 아닌 것으로 보여집니다. 

그리고 private method들은 클래스 코드 가장 아래쪽으로 모두 모아주세요.

2020-02-28 00:11 UTC, wheejuni commented on src/main/java/com/codessquad/qna/user/UserController.java
>                                          String userEmail) {
한 라인의 길이가 너무 짧게 lint되고 있는 건 아닐지요? 이정도는 그냥 한 줄로 기입해도 될 것 같은데요. 
https://naver.github.io/hackday-conventions-java/#line-length-120

2020-02-28 00:11 UTC, wheejuni commented on src/main/java/com/codessquad/qna/user/UserController.java
>              userRepository.save(user);
save 한 후 결과물을 return하는 것을 추천합니다.

2020-02-28 00:15 UTC, ksundong commented on src/main/java/com/codessquad/qna/error/ErrorController.java
>      @GetMapping("/user_not_found")
에고 생각해보니 잘못했네요 왜 snakecase로 했지...
감사합니다 수정할게요!

2020-02-28 00:17 UTC, ksundong commented on src/main/java/com/codessquad/qna/user/User.java
> +
한 번 생각해보고 공부해보겠습니다
JPA너무 어렵네요 ㅠㅠ

2020-02-28 00:18 UTC, ksundong commented on src/main/java/com/codessquad/qna/user/UserController.java
>          model.addAttribute("httpMethod", "POST");
안그래도 수정할 때 비밀번호 수정이 불가해서 템플릿을 추가하려고 합니다!!

2020-02-28 00:18 UTC, ksundong commented on src/main/java/com/codessquad/qna/user/UserController.java
>                                          String userEmail) {
hardwrap 길이를 늘려보겠습니다

2020-02-28 01:47 UTC, ksundong commented on src/main/java/com/codessquad/qna/question/Answer.java
> +    private Question question;
오, 저는 다 붙여야 하는 줄 알아서... 반영할게요!

2020-02-28 01:52 UTC, ksundong commented on src/main/java/com/codessquad/qna/user/UserController.java
>              userRepository.save(user);
다른 리뷰에서 보았던 내용인 것 같은데, 확인 후에 적용하겠습니다.

2020-02-28 06:03 UTC, honux77 commented on src/main/java/com/codessquad/qna/common/CommonUtility.java
> +public class CommonUtility {
스프링에 있는 유틸리티 클래스 같은 경우도 HttpUtils 라는 이름을 사용하네요.  메소드가 있다면 Utils 아니라면 Constants가 좋을 것 같아요.

2020-02-28 06:04 UTC, honux77 commented on src/main/java/com/codessquad/qna/error/ErrorController.java
>      @GetMapping("/user_not_found")
ㅋㅋ 근데 사실 대문자도 비추인데 포비도 updateForm을 사용하더라고요. 고민...

2020-02-28 06:06 UTC, honux77 commented on src/main/java/com/codessquad/qna/user/User.java
> +
아 맞아요. 저도 Id가 없어서 false 난 적이 있었거든요. 일반적인 경우라면 email 같은유니크한 값 비교만으로도 충분한 것 같았어요.

2020-02-28 06:07 UTC, honux77 commented on src/main/java/com/codessquad/qna/user/UserController.java
>                                          String userEmail) {
저도 80줄 쓰는데 조금 늘려도 되는군요. 80줄 너무 옛날 방식인가 봐요.

2020-02-28 06:07 UTC, honux77 commented
빠르게 잘 짜고 있는 듯. 화이팅!

2020-02-28 06:08 UTC, merged

2020-02-28 12:18 UTC, ksundong commented on src/main/java/com/codessquad/qna/error/ErrorController.java
>      @GetMapping("/user_not_found")
@honux77 스프링 펫 클리닉도 카멜케이스더라고요! 🤔