[Sigrid] Step2 구현 완료
code-squad/java-qna pull request #172
Opened 2020-02-27 14:58 UTC by jypthemiracle

# 구현 완료사항
* H2 DB 추가 및 설정
* 회원가입 및 사용자 목록 페이지 구현
* 개인정보 수정 기능 구현
* 게시글 정보 수정 기능 구현

# 학습하고 경험한 사항
* H2 DB 사용을 통한 Spring Boot JPA 활용 경험
* Spring Boot의 웹 계층(Dto, Entity) 내용 학습 및 관련 API 설계 경험
* HTTP PUT 메소드를 활용한 경험
* HTTP template을 직접 제작함으로서 프론트 페이지로 넘어가는 마크업 문법을 학습
* Lombok 라이브러리, Builder 패턴의 학습과 사용

# 배포한 페이지 링크
https://java-qna-step2-jypthemiracle.herokuapp.com/

2020-02-28 22:55 UTC, wheejuni requested changes
수고 많으셨습니다.
전반적으로 `spring-data-jpa` 의 부가기능을 많이 활용해보려 노력하신 것 같은데, 
지금 단계를 뛰어넘으려는 노력을 하신 것 응원하고 싶고, 한편으론 걱정되는 부분도 있습니다. 

지금 구현하신 패턴이나 사용하신 부가기능들의 작동 원리에 대해 더 파고드는 학습을 해 보길 권합니다. 
쓰지 않았다면 상관없지만, 일단 사용한 이상, 개발자라면 내가 사용하는 기술이 어떤 취지에서 어떻게 작동하는 기술인지 정확히 이해하는 것은 필수적일 것입니다. 

코멘트로 질문을 몇 개 남겨드렸는데 **꼭 답변해주세요.** 기다릴게요 ㅋㅋ
수고 많으셨어요.

2020-02-28 22:55 UTC, wheejuni commented on build.gradle
> +	jcenter() //최근에는 jcenter로 이동하고 있는 추세이다.
정말요? 몰랐네요. 
그런데 디펜던시를 사용하다보면 사실 또 특정 디펜던시는 특정 nexus에서만 배포되고 있는 경우도 있어서요, 굳이 추세를 따르기보단 사용할 디펜던시가 어디에 있는지 파악하고, 그 저장소만 추가해주면 됩니다.

2020-02-28 22:55 UTC, wheejuni commented on src/main/java/com/codessquad/qna/IndexController.java
> +@RequiredArgsConstructor
의존성 주입과 DI Framework에 대한 이해가 더 생기실때까지 `@RequiredArgsConstructor` 를 통한 생성자 주입은 사용을 잠시 미뤄주세요.

2020-02-28 22:55 UTC, wheejuni commented on src/main/java/com/codessquad/qna/controller/UsersRepository.java
> +  @Query("SELECT p FROM Users p ORDER BY p.Id DESC")
`@Query` 애노테이션을 쓰는 시도는 좋았습니다만, 정확히 이해하고 **꼭 필요할 때만 사용하는게 좋습니다.** 
*질문: 지금 `@Query` 애노테이션 안에 쓰신 쿼리, JPA가 SQL로 이해할까요?*

+) 그리고 이렇게 하지 않아도 내림차순 정렬하는 방법이 있었을 겁니다. 찾아보세요!

2020-02-28 22:55 UTC, wheejuni commented on src/main/java/com/codessquad/qna/service/posts/PostsService.java
> +  @Transactional(readOnly = true)
모든 메소드에 `@Transactional` 이 필요했을까요?

`JpaRepository` 를 주입받는 서비스 클래스에서 `@Transactional` 의 역할범위는 어디까지일까요? 그리고 어떤 역할을 하는거죠?

2020-02-28 22:55 UTC, wheejuni commented on src/main/java/com/codessquad/qna/service/posts/PostsService.java
> +  }
`Update` 나 `Save` 를 수행했다면 해당 객체를 그대로 리턴해주는 것이 가장 안전합니다. 
어차피 save된 객체가 Id를 갖고 있는데, 그걸 굳이 꺼내서 리턴해 줄 필요는 없습니다.

2020-02-28 22:55 UTC, wheejuni commented on src/main/java/com/codessquad/qna/web/dto/PostsListResponseDto.java
> +  public PostsListResponseDto(Posts entity) {
생성자로 바로 받기보다는, 
다양한 경우를 위한 생성자를 `protected` 나 `private` 으로 선언한 뒤에, 스태틱 메소드로 객체를 만들어주는 방식도 한번 생각해보세요. 
`PostsListResponseDto.of(Posts entity)` 같은 형태로요.

2020-02-28 22:55 UTC, wheejuni commented on build.gradle
> +group 'com.jojoldu.book'
헐~ ㅋㅋㅋㅋ

2020-02-28 22:55 UTC, wheejuni commented on src/main/java/com/codessquad/qna/domain/BaseTimeEntity.java
> +@EntityListeners(AuditingEntityListener.class)
`@EnableJpaAuditing` 이 보이지 않는데 잘 작동하나요?
그리고 어떤 원리로 작동하는 걸까요?

2020-02-29 00:50 UTC, honux77 commented on build.gradle
> +	jcenter() //최근에는 jcenter로 이동하고 있는 추세이다.
ㅎㅎㅎ 이거는 동욱님 블로그를 보고 한 듯

2020-02-29 00:55 UTC, honux77 commented
마스터 브랜치라서 close 합니다...

2020-02-29 00:55 UTC, closed without merging

2020-02-29 04:26 UTC, jypthemiracle commented
앗, 제가 실수로 마스터 브랜치로 보냈네요. 그래도 여기 PR에 리뷰를 달았으니 쓰레드를 계속 이어가겠습니다.

2020-02-29 04:34 UTC, jypthemiracle commented on build.gradle
> +	jcenter() //최근에는 jcenter로 이동하고 있는 추세이다.
전반적으로 그레이들의 build.gradle의 의미를 파악하려고 노력했습니다.

2020-02-29 04:34 UTC, jypthemiracle commented on src/main/java/com/codessquad/qna/IndexController.java
> +@RequiredArgsConstructor
알겠습니다. 다음 스텝에서는 @Autowired를 활용하여 재설계하도록 하겠습니다.

2020-02-29 08:32 UTC, jypthemiracle commented on src/main/java/com/codessquad/qna/controller/UsersRepository.java
> +  @Query("SELECT p FROM Users p ORDER BY p.Id DESC")
1. @Query 어노테이션 내부에 적힌 쿼리는 Hibernate Query Language라고 하더라구요. Hibernate(JPA)를 사용하는 이유가 관계형 데이터베이스에 직접 접근할 경우 객체지향의 원칙에 어긋날 수 있으므로, 패러다임을 중간에서 대신 해석해주는 역할을 맡기는 것이라고 학습했습니다. 따라서 관계형 언어인 SQL이 아니라 Hibernate에서 객체-관계가 매핑된 대상으로 직접 접근(ex. Users)한다고 정리했습니다. 그런데 제가 잘 이해한 것인지는 모르겠네요 (머쓱)

2020-02-29 08:52 UTC, jypthemiracle commented on src/main/java/com/codessquad/qna/controller/UsersRepository.java
> +  @Query("SELECT p FROM Users p ORDER BY p.Id DESC")
2. JPARepository에서는 List<Posts> ....ByOrderDesc 형태로 기본제공하는 것으로 보이는데, CRUDRepository에서는 descending하는 방법을 [스프링 문서](https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/repository/CrudRepository.html)에서 찾지 못했습니다. 혹시 검색할 수 있는 힌트가 있을까요?

2020-02-29 08:53 UTC, jypthemiracle commented on src/main/java/com/codessquad/qna/controller/UsersRepository.java
> +  @Query("SELECT p FROM Users p ORDER BY p.Id DESC")
2. JPARepository에서는 ```List<Posts> ....findByUsersByUserIdDesc()``` 형태로 기본제공하는 것으로 보이는데, CRUDRepository에서는 descending하는 방법을 [스프링 문서](https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/repository/CrudRepository.html)에서 찾지 못했습니다. 혹시 검색할 수 있는 힌트가 있을까요?

2020-02-29 08:57 UTC, jypthemiracle commented on build.gradle
> +group 'com.jojoldu.book'
ㅋㅋㅋㅋ group이 그래도 딸려왔네요.

2020-03-01 03:50 UTC, jypthemiracle commented on src/main/java/com/codessquad/qna/service/posts/PostsService.java
> +  @Transactional(readOnly = true)
1. ```@Transactional``` 어노테이션은 DB의 상태를 변화시키는 경우에 사용하는 것이 적합하다고 생각합니다. 커밋한 코드에는 모든 메소드에 어노테이션이 붙어있지만, save나 update에만 사용하는 것이 유의미하겠군요.
2. ```@Transactional``` 을 사용할 경우 영속성 컨텍스트에서 엔티티의 값에 변경사항이 나타날 경우 이를 알아서 DB에 commit한다고 학습했습니다. 어쩌다가 JPA까지도 조금씩 공부하면서 [정리](https://github.com/jypthemiracle/This-Week-I-Learned/blob/master/Feb%202020/2020.02.29/JPA%EC%97%90%20%EB%8C%80%ED%95%9C%20%EA%B0%84%EB%9E%B5%EC%A0%81%EC%9D%B8%20%EC%A0%95%EB%A6%AC.md) 하고 있는데, 스스로도 좀 많은 것을 하고 있지 않은가 하는 생각도 들게 되네요 ㅎㅎ

2020-03-01 04:09 UTC, jypthemiracle commented on src/main/java/com/codessquad/qna/service/posts/PostsService.java
> +  }
질문이 있습니다.
1. 해당 객체를 그대로 리턴해주면 안전하다는 것이 어떤 의미일까요? 안전하다는 것의 의미를 알고 싶습니다.
2. id를 리턴해주면 JSON data type으로 이해하던데, 객체를 JSON 타입으로 변경해주려면 어떻게 해야 할까요? ```index.js``` 에서 JSON 반환을 예측하지 못하도록 해도 될까요? [index.js 107번 라인](https://github.com/jypthemiracle/java-qna/blob/539f1a79ae11e3b9571d5820adf408aac77c769b/src/main/resources/static/js/app/index.js#L107)

2020-03-01 04:14 UTC, jypthemiracle commented on src/main/java/com/codessquad/qna/web/dto/PostsListResponseDto.java
> +  public PostsListResponseDto(Posts entity) {
음.. 다양한 경우라는 것이 1) title이 수정되는 경우 2) contents가 수정되는 경우 3) title, contents 둘 다 수정되는 경우 를 각각 따져보자는 의미이실까요?

2020-03-01 04:17 UTC, jypthemiracle commented on src/main/java/com/codessquad/qna/domain/BaseTimeEntity.java
> +@EntityListeners(AuditingEntityListener.class)
1. ```@EnableJpaAuditing``` 은 ```QnaApplication.java``` 에서 ```main``` 메소드 실행 이전에 추가했더니 동작하더라구요.

2020-03-01 06:07 UTC, jypthemiracle commented on src/main/java/com/codessquad/qna/service/posts/PostsService.java
>    @Transactional(readOnly = true)
```@Transactional``` 의 사용과 엔티티의 생명주기에 대한 학습 정리 내용: [링크](https://github.com/jypthemiracle/This-Week-I-Learned/blob/master/Feb%202020/2020.02.29/JPA%EC%97%90%20%EB%8C%80%ED%95%9C%20%EA%B0%84%EB%9E%B5%EC%A0%81%EC%9D%B8%20%EC%A0%95%EB%A6%AC.md) 하고

2020-03-01 06:07 UTC, jypthemiracle commented on src/main/java/com/codessquad/qna/service/posts/PostsService.java
> +        .map(posts -> new PostsListResponseDto(posts))
아직 람다가 익숙하지 않아 클래식한 방식을 적용하였음.

2020-03-01 06:09 UTC, jypthemiracle commented on src/main/java/com/codessquad/qna/domain/BaseTimeEntity.java
> +@EntityListeners(AuditingEntityListener.class)
JPA Auditing이 어떠한 원리로 동작하는 지 학습한다.
작동 원리를 정리해보면 다음과 같다 (맞는 지는 피드백이 필요하다.)
	가. 모든 엔티티는 생명주기가 존재한다.
	나. EntityListener 클래스를 통해 콜백 리스너를 지정한다. 생명 주기에 변동과 수정사항이 발생하는 이벤트가 발생할 경우 지정된 리스너에게 이벤트 발생 사실을 고지받는다.
	다. Spring Data JPA는 ```AuditingEntityListener``` 라는 리스너를 미리 만들어두었다. 이를 주입받아 사용하면 된다.
* 다음의 링크에 학습 내용을 정리하고 있다. [링크](https://github.com/jypthemiracle/This-Week-I-Learned/blob/master/Mar%202020/2020.03.01/JPA%20Auditing%EC%97%90%20%EB%8C%80%ED%95%9C%20%EA%B0%84%EB%9E%B5%ED%95%9C%20%EC%A0%95%EB%A6%AC.md)

2020-03-01 11:15 UTC, wheejuni commented on src/main/java/com/codessquad/qna/IndexController.java
> +@RequiredArgsConstructor
아뇨, @Autowired를 사용하시라는 것은 아니고, lombok 도움 없이 직접 생성자를 작성해달라는 의미였어요. 
스프링 컴포넌트에 몇 개의 의존성이 주입되는지가 사실 클래스/컴포넌트 분리 포인트를 잡는데 큰 도움이 되는데 롬복을 사용하면 무의식적으로 아무거나 쉽게 주입받게 되거든요. 
아직 스프링 컴포넌트 설계에 익숙하시지 않으니, 생성자에 파라미터가 얼마나 많이 늘어나는지를 직접 눈으로 확인하시면서 구현하시라는 조언 드렸던 거였습니다. ㅎㅎ

2020-03-01 11:19 UTC, wheejuni commented on src/main/java/com/codessquad/qna/controller/UsersRepository.java
> +  @Query("SELECT p FROM Users p ORDER BY p.Id DESC")
1. HQL/JPQL 이라고 합니다. 
객체-관계 매핑에 있어, 매퍼가 특정 RDBMS에 종속되면 안 되므로 중간 언어를 사용하는 측면이 큽니다. 

2. `spring-data`가 애플리케이션 콘텍스트에 프록시 빈을 띄울 때, `Repository<T, ID>` 를 상속받는 인터페이스 중 `@NoRepositoryBean`이 선언되지 않은 모든 인터페이스의 메소드를 파싱해서 프록시 빈을 띄우게 되고요, 

`CrudRepository` 도 물론 `Repository` 의 서브타입이므로 사실 이 부분이 당연히 지원됩니다. 
링크를 거신 문서는 `CrudRepository` 의 Javadoc이라고 불러야 하고, 사실 "스프링 문서" 나 "스프링 레퍼런스" 라고 하는 문서는 가이드성 문서나 레퍼런스 문서를 보통 칭하는 말입니다. 해당 자바독은...자바 객체 그 자체에 대한 명세이기때문에 spring-data 가 어떻게 쿼리 메소드를 파싱하고 쿼리를 만드는지에 대해서는 알려주지 않을 겁니다. 

검색어 힌트는 spring data query methods 입니다. 힘내세요!

2020-03-01 11:21 UTC, wheejuni commented on src/main/java/com/codessquad/qna/web/dto/PostsListResponseDto.java
> +  public PostsListResponseDto(Posts entity) {
생성자니까 엄밀히 말하면 수정은 아니죠. 
해당 DTO를 만들때 꼭 모든 필드에 값이 들어가야 하는 것은 아닐테니 말입니다. 
그리고 해당 DTO와 엔티티가 꼭 1대1로 매칭되어야 하는것도 아니죠.

2020-03-01 11:25 UTC, wheejuni commented on src/main/java/com/codessquad/qna/service/posts/PostsService.java
> +  @Transactional(readOnly = true)
음 그럼 이제 질문을 달리 드려볼게요. 
`@Transactional` 을 쓰지 않으면 영속성 컨텍스트는 언제 flush될까요?
그리고 save와 update외에 사용될 상황이 또 있을 것 같은데요. 지금 단계에서 대답 못해도 되는 질문입니다. 과연 언제일지 한번 생각해 보세요.

2020-03-01 11:27 UTC, wheejuni commented on src/main/java/com/codessquad/qna/service/posts/PostsService.java
> +  }
1. 영속성 컨텍스트가 dirty check를 하고 flush한 객체 그 자체를 리턴해주는 로직을 구현하는 것이 명시적으로 transaction이 종료되었다는 의미가 됩니다. 지금 메소드는 파라미터로 받은 id값을 리턴하기에, 사실 명시적으로 영속성 콘텍스트가 종료되고 그 결과값이 리턴되어 flush되었다라는 의미로 코드가 읽히지 않습니다. 

2. DTO를 만들어서 내보내면 되죠.

2020-03-02 11:40 UTC, jypthemiracle commented on src/main/java/com/codessquad/qna/IndexController.java
> +@RequiredArgsConstructor
의도를 파악했습니다. 다음 스텝에서는 de-lombok 하여 구현해보겠습니다.

2020-03-02 11:51 UTC, jypthemiracle commented on src/main/java/com/codessquad/qna/controller/UsersRepository.java
> +  @Query("SELECT p FROM Users p ORDER BY p.Id DESC")
2번 관련해서, 아직 이해가 되지 않습니다. JPA도 공부할 사항이 참 많군요 @.@
스텝을 진행하면서 시간을 갖고 학습해보겠습니다!

2020-03-02 12:11 UTC, jypthemiracle commented on src/main/java/com/codessquad/qna/service/posts/PostsService.java
> +  @Transactional(readOnly = true)
1. @Transactional을 쓰지 않으면 직접 ```flush``` 명령을 내려주지 않으면 변경이 되지 않는 것으로 우선 생각을 해 보았습니다.
2. 혹시 UsersService에 한정하여 주시는 질문이실까요? 현재 시점으로서 저는 inseperable한 operations들이 붙어있을 경우에 Transaction으로 취급해야 한다고 받아들였습니다. 그렇다면, ```findById()``` 에서 임의의 Users 객체에서 필요한 일부 필드 값이 누락되어 있다고 가정했을 때 조회 작업을 멈추도록 구현해볼 수도 있지 않을까 생각해보았습니다.