Submit Step3 : 스프링 부트로 QA 게시판 구현 1
code-squad/java-qna pull request #182
Opened 2020-03-02 13:25 UTC by Hyune-c

### # Heroku
https://codesquad-qnaboard.herokuapp.com/

### # 기능 구현
- Answer 을 제외하고 구현 ... complete
- 에러 핸들링에 대한 구현
  - CustomError ... complete
  - DefaultError ... working

### # Refactoring 예정
- Error 핸들링에 대한 개선 
  - Enum Stirng 비교가 아닌 더 좋은 방법을 고민 중입니다.

### # 질문 
- Error 처리 방법이 적절한지 질문 드립니다.
  - Enum 을 좀 더 잘 사용해보고 싶은데.. 어떻게 해야될지 감이 잘 안잡힙니다.
  - @ControllerAdvice 를 통해 에러처리를 하면서 CustomException 들은 잘 처리 했는데, @ExceptionHandler(Exception.class) 를 통한 정의되지 않은 에러가 되지 않았습니다. 
무엇을 잘못한걸까요..? 
- Optional 사용을 하면서 orElseThrow 를 사용해보았습니다. 적절한 사용법일까요?

2020-03-07 01:07 UTC, wheejuni requested changes
안녕하세요. 리뷰가 늦어 죄송합니다. 

질문에 대한 답변도 함께 드릴게요.

1 번 질문은 코드상 코멘트로 답변 드렸고, 
`@ResponseStatus` 에 대해서는 이미 보셨을 줄로 알지만 https://springboot.tistory.com/25 링크도 참고해 보세요. 
아무런 Exception Resolver에 걸리지 않은 상태여야 Spring MVC가 제공하는 exception resolver에 pick up되어 처리될 수 있는 애노테이션인 겁니다. 

2. 잘 하셨어요. 
3. `Service` 클래스가 없어서 생기는 문제들인데요, 지금 단계에선 고민 안해도 됩니다. 다만 다음 스텝에서부터는 조금씩 고민해주세요. 
4. https://jojoldu.tistory.com/361 에서 보시면 알 수 있듯이 JSON 기반 요청/응답 본문의 직렬화/역직렬화를 위해 사용하는 애노테이션이구요, 지금 View Template 기반 구현에서는 해당사항이 없는 애노테이션입니다. 
**getter를 사용하는 것이 절대 나쁜 접근이 아니니 그대로 하셔도 됩니다.**

충실한 답변이 되었으면 좋겠습니다! 다른 추가 질문 있으시면 여기에 답글로 남겨주세요. 감사합니다~

2020-03-07 01:07 UTC, wheejuni commented on src/main/java/com/codessquad/qna/commons/CustomErrorCode.java
> +  BAD_REQUEST(HttpStatus.BAD_REQUEST.getReasonPhrase());
위 케이스들은 다 문자열을 하드코딩했는데 여기선 다른 상수를 불러왔네요. 특별한 이유가 있나요.

2020-03-07 01:07 UTC, wheejuni commented on src/main/java/com/codessquad/qna/commons/CustomErrorController.java
> +  @ExceptionHandler(Exception.class)
이렇게 선언하면 아무런 예외도 처리할 수가 없습니다. 
생각해보면 아래 `ForbiddenException` 이나 `UserException` 도 모두 다 `Exception` 의 서브클래스에요. 
왜냐면 `RuntimeException` 이 `Exception` 의 서브클래스이고 지금 작성하신 커스텀 에외들이 모두 `RuntimeException` 을 상속했으니까요. https://docs.oracle.com/javase/7/docs/api/java/lang/RuntimeException.html

하위 클래스에 대한 `@ExceptionHandler` 가 있다면 상위 클래스 예외를 catch하는 exception resolver는 무시되므로(별도의 order 설정이 없는 이상 말이죠) 이미 다양한 알려진 예외에 대해 기본 exception resolver를 제공하는 Spring MVC가 이 어드바이스를 사용하지 않은 것은 당연한 것입니다. 

https://stackoverflow.com/questions/38462588/order-of-exceptionhandler 같은 주제로 고민한 사람이 있는 것 같아 링크 가져와봅니다.

2020-03-07 01:07 UTC, wheejuni commented on src/main/java/com/codessquad/qna/commons/CustomErrorController.java
> +    }
고민을 많이 하신 것이 티가 나네요. ㅠ
그러나 각 경우에 대해 `UserException` 을 상속하는 다른 커스텀 예외가 있었으면 더 좋았을 뻔 했습니다.

2020-03-07 01:07 UTC, wheejuni commented on src/main/java/com/codessquad/qna/commons/CustomErrorController.java
> +      model.addAttribute("notMatchedUser", true);
여기두요. 상단 코멘트 참고해주세요

2020-03-07 01:07 UTC, wheejuni commented on src/main/java/com/codessquad/qna/commons/Utils.java
> +public class Utils {
클래스 이름 다시 고민해주세요.

2020-03-07 01:07 UTC, wheejuni commented on src/main/java/com/codessquad/qna/question/Question.java
>    @GeneratedValue(strategy = GenerationType.IDENTITY)
`GenerationType.IDENTITY` 는 어떤 원리로 작동하는 거죠?

2020-03-07 01:07 UTC, wheejuni commented on src/main/java/com/codessquad/qna/question/Question.java
> +    return this.userId.equals(user.getUserId());
`User` 클래스에게 동질성의 판단을 위임해야 하는 것은 아니었을지요.

2020-03-07 01:07 UTC, wheejuni commented on src/main/java/com/codessquad/qna/question/QuestionController.java
> +    Utils.getSessionedUser(session);
가져온 결과물을 어디에도 쓰지 않네요. 어떻게 된 거죠?

2020-03-07 01:07 UTC, wheejuni commented on src/main/java/com/codessquad/qna/user/User.java
> +@Data
`@Data` 가 자동생성해주는 메소드는 어떤 것들이 있나요?

2020-03-07 01:07 UTC, wheejuni commented on src/main/java/com/codessquad/qna/user/User.java
> +@NotNull
클래스 레벨에서 `@NotNull` 을 사용하면 어떤 유효성 검증을 하게 되는 건가요?

2020-03-07 08:38 UTC, Hyune-c commented on src/main/java/com/codessquad/qna/commons/CustomErrorCode.java
> +  BAD_REQUEST(HttpStatus.BAD_REQUEST.getReasonPhrase());
@wheejuni 하드코딩한 것들은 커스텀 익셉션을 위함이고, 아래의 것은 표준 정의 익셉션을 가져오기 위한 의도였습니다.

2020-03-07 08:40 UTC, Hyune-c commented on src/main/java/com/codessquad/qna/commons/CustomErrorController.java
> +    }
@wheejuni 
말씀하신게 이해가 잘 안되서요.. 예외 종류를 묶을 수 있는 커스텀 클래스를 만들라는 뜻이신가요? 아직 구현은 못했지만 Enum 을 적용해보려고 시도 했었습니다. (물론 실패............)

2020-03-07 08:42 UTC, Hyune-c commented on src/main/java/com/codessquad/qna/question/Question.java
>    @GeneratedValue(strategy = GenerationType.IDENTITY)
@wheejuni 키 생성을 DB 에 위임하는 것으로 1씩 상승되는 것으로 알고 있습니다.

2020-03-07 08:43 UTC, Hyune-c commented on src/main/java/com/codessquad/qna/question/Question.java
> +    return this.userId.equals(user.getUserId());
@wheejuni 맞는거 같아요.. 수정해보겠습니다.

2020-03-07 08:45 UTC, Hyune-c commented on src/main/java/com/codessquad/qna/question/QuestionController.java
> +    Utils.getSessionedUser(session);
@wheejuni 
Desc : Utils.getSessionedUser() 를 통해 login 여부를 검증합니다.
get 메소드 안에 sessionUser 가 null 인 경우 error 처리를 하게하였기에 위에서는 별도의 예외처리를 하지 않았습니다.
하지만 말씀을 듣고보니 메소드명만으로는 의문이 드는 로직일거 같은데.. 메소드 안에서 error 처리를 하더라도 명시적으로 한번 더 처리를 하는게 맞을까요?

2020-03-07 08:51 UTC, Hyune-c commented on src/main/java/com/codessquad/qna/user/User.java
> +@Data
@wheejuni @Getter, @Setter, @ToString, @EqualsAndHashCode, @RequiredArgsConstructor 를 생성해주는 lombok 어노테이션 입니다.

2020-03-07 08:51 UTC, Hyune-c commented on src/main/java/com/codessquad/qna/user/User.java
> +@NotNull
@wheejuni 
https://github.com/Hyune-c/TIL/blob/master/Spring/Annotation.md#javaxvalidation-%EB%B9%88-%EA%B2%80%EC%A6%9D
위와 같이 정리하였습니다.

2020-03-07 16:07 UTC, Hyune-c commented
@wheejuni 
리뷰를 받은 후 선택 사항을 완료하여 추가 커밋하였습니다.

### # step3 Refactoring
- validateUserId() 메소드의 이동 ... working
- Utils 에서 CommonUtils 로 이름 변경 ... complete 

### # 기능 구현
- Answer 구현하기 실습(선택) 
    - 답변 목록은 모두가 볼 수 있습니다. ... complete
    - 답변 작성은 로그인한 사용자만 가능합니다. ... complete
    - 답변 삭제는 자신의 것만 가능합니다. ... complete

### # 질문
- 여러 곳에서 쓰일 수 있는 메소드를 CommonUtils 로 모으다 보니 DB 에 접근할 때가 애매해졌습니다.  
    - 아래 메소드는 static 이며 Repository 를 매개변수로 전달받게 만들었습니다.
    - Repository 는 Singleton 이기에 전역에서 접근하려 했는데 @autowired 는 static 적용을 할 수가 없었습니다.
    - 어쩔 수 없이 매개변수로 전달하는 형태로 구현했는데 의존성 면에서 좋아보이지 않아 고민됩니다.  

```java
public static Question getQuestion(QuestionRepository questionRepository, Long id) {
```

2020-03-08 13:14 UTC, honux77 commented on src/main/java/com/codessquad/qna/question/QuestionController.java
> +    Utils.getSessionedUser(session);
이름만으로 내용을 알기 어렵네요. 
사소하지만 Utils 는 static import를 하고 checkLoginOrError(session) 뭐 이런 정도의 이름이면 좋았을 것 같습니다.

2020-03-08 13:18 UTC, honux77 commented on src/main/java/com/codessquad/qna/user/User.java
> +@Data
가능하면 연습 단계에서는 Lombok을 안 쓰면 좋겠어요. 귀찮더라도 일단은 하나씩 타이핑하는게 좋지 않을까요?

2020-03-08 13:19 UTC, merged