[Dion] Step5 완료했습니다.
code-squad/java-qna pull request #185
Opened 2020-03-04 05:54 UTC by ksundong

# STEP4 리뷰 적용

1. CommonConstant를 분리하였습니다.
2. 불필요한 Setter를 제거하였습니다.
3. 객체 자신의 userEmail을 가져오는 부분을 this.userEmail로 변경하였습니다.
   - userEmail은 email로 바꾸는게 좋을 것 같다고 하셨는데, 약간 변수명의 일관성을 유지하려고 그렇게 정했던 것인데, 혹시 문제가 된다면 변경하겠습니다. 

# STEP5 진행 전 개인적으로 해보고 싶었던 것 적용

1. 패키징을 의미있는 단위로 하고싶어서 바꿨습니다.
   - api: api 요청은 이 패키지에서 받습니다.
   - common: 공통 패키지는 여기에 모아둡니다.
      - constants: 상수를 담는 클래스를 모아둡니다.
      - error: 에러처리를 담당하는 패키지입니다.
         - exception: 사용자 정의 Exception을 담당하는 패키지입니다.
      - utils: 유틸리티성 클래스는 여기에 모아둡니다.
   - web: web 요청은 이 패키지에서 받습니다.
2. 이미지 업로드 기능을 구현하고 싶었으나, File I/O에 대한 이해 부족으로 이미지 url을 올리는 것에 만족해야했습니다. 검색해보니 heroku에서는 AWS S3을 사용하는 것을 더 권장한다고 해서 나중에 이것을 사용해볼까 생각하고 있습니다.
3. 다른 분들의 PR을 보면서 `HttpSessionUtils`라는 클래스로 처리해주는게 인상깊어서 적용해보았습니다.
4. 에러처리를 위해서 CustomException을 사용해보았습니다. 현재 남아있는 문제는 WhiteLabelError 페이지가 아닌 ErrorResponse를 json으로 응답한다는 점입니다.

# STEP5 진행

1. AJAX로 답변 추가 기능 구현
   - JPA때문에 너무 골치가 아팠습니다. (무환 순환 참조(?)에 의한 StackOverFlow 발생)
   - 자료에선 새로 추가된 답변을 prepend로 앞에 붙이는데, 저는 답변의 경우 오름차순 정렬이라 아래에 붙이도록 하였습니다.
   - 답변의 개수도 출력해주는데, 같이 바뀌도록 처리하였습니다.
   - format을 해줄 때, 데이터 유형별로 묶어서 더 읽기 좋게끔 하고자 하였습니다.
2. AJAX로 답변 삭제 기능 구현
   - Result를 사용하라고 하셨는데 Result라는 클래스가 존재하지 않아. 이전 기수분의 코드를 가져와 썼습니다.
   - AJAX로 추가된 답변의 삭제 기능의 구현도 같이 적용하였습니다.

# 의문점

1. 통상적인 경우 RestController 와 Controller가 같은 프로젝트로 운영되는지 궁금합니다.

2. Optional로 에러를 발생시키지않고 조건문을 사용해서 처리해줄 수 있다는 말이 잘 이해가 가지 않습니다.  
Optional을 쓰는 이유가 null처리를 직접하지 않고, Optional에서 처리해주기 위함이라고 생각했는데...  
아니면 함수형 프로그래밍적으로 사고를 해서 filter를 이용해야 하는걸까요? 좀 더 자세히 알고 싶습니다.

감사합니다!

2020-03-07 13:23 UTC, tramyu commented
### 의문점 

> 통상적인 경우 RestController 와 Controller가 같은 프로젝트로 운영되는지 궁금합니다.

최근에는 리액트나 뷰, 앵귤러 등을 이용해 프론트를 구성하다 보니 Controller와 RestController가 동시에 존재하는 경우는 거의 없었던 것 같습니다. (같이 묶어서 배포되더라도 Controller를 굳이 정의할 필요는 없어서 사용하지 않았어요)

템플릿 엔진 + REST API의 구조로 된 프로젝트라면 굳이 프로젝트를 분리하지 않고 같은 프로젝트 내에서 운영할 것 같네요


> Optional로 에러를 발생시키지않고 조건문을 사용해서 처리해줄 수 있다는 말이 잘 이해가 가지 않습니다.
> Optional을 쓰는 이유가 null처리를 직접하지 않고, Optional에서 처리해주기 위함이라고 생각했는데...
> 아니면 함수형 프로그래밍적으로 사고를 해서 filter, map등을 이용해야 하는걸까요? 좀 더 자세히 알고 싶습니다.

`Optional로 에러를 발생시키지않고 조건문을 사용해서 처리해줄 수 있다는 말` 이 말의 전문을 한번 보고 싶네요 어떤 의미로 작성하신건지 한줄만 보고는 파악이 힘들어서요

Optional을 사용하게 되는 경우 null인 객체에 대해 직접 함수를 호출하거나 하는 경우가 없으니 `NullPointerException`의 빈도는 줄어들 수 있을 것 같습니다. 이외에 조건문을 사용해 처리한다는 건 orElseThrow나 ifPresent 등을 이용할 수 있다는 게 아닐까 싶은데 전문을 보지 못해서 어떤 의미로 작성한건지는 파악하기 힘드네요

2020-03-07 13:39 UTC, kyucumber requested changes

2020-03-07 13:39 UTC, tramyu commented on src/main/java/com/codessquad/qna/web/question/Question.java
> +    @JsonIgnore
알고 계실것 같긴 하지만

`@JsonIgnore` 대신 `@JsonManagedReference, @JsonBackReference` 등을 활용할수도 있습니다.

https://www.baeldung.com/jackson-bidirectional-relationships-and-infinite-recursion

그리고 나중에 어느정도 여유가 생기시고, 충분한 학습이 이루어진다면 엔티티를 리턴하는걸 지양하고 dto 등을 리턴하는게 좋습니다. (발생하셨다고 하는 양방향 연관관계간의 순환 참조, 영속성 컨텍스트 문제, 그리고 리턴되는 값은 언제든 변경될 수 있는데 그때마다 엔티티를 변경해줄 순 없으니까요)

2020-03-07 13:39 UTC, tramyu commented on src/main/java/com/codessquad/qna/web/user/User.java
>      private String userEmail;
User라는 엔티티 하위에 email이 들어가는거라 user라는 prefix는 제거되어도 되지 않을까요?

조인을 해야하는 쿼리를 작성할 때야 column 이름들이 같은 경우 혼란을 줄 수 있지만 email의 경우 그렇게 많은 곳에서 사용할 것 같지도 않아서 앞의 user를 지워주어도 어떤 내용인지 파악이 가능할 것 같네요.

2020-03-07 13:39 UTC, tramyu commented on src/main/java/com/codessquad/qna/web/user/User.java
> +    public User(String userId, String userPassword, String userName, String userEmail, String userProfileImage) {
혹시 외부에서 호출되지 않을 생성자라면 private으로 전환할수도 있을 것 같네요

2020-03-07 13:39 UTC, tramyu commented on src/main/java/com/codessquad/qna/web/user/User.java
> +        if (!"".equals(newPassword)) {
해당 `StringUtils`의 의존성이 포함되어 있는지 모르겠는데
`package org.springframework.util` 패키지의 `StringUtils`의 `isEmpty`를 활용하실수도 있을것 같네요

```java
public static boolean isEmpty(@Nullable Object str) {
    return (str == null || "".equals(str));
}
```

2020-03-07 13:39 UTC, tramyu commented on src/main/java/com/codessquad/qna/web/user/User.java
>      private String userEmail;
다른 값들도 동일합니다.

취향 차이라 상관은 없지만 한번 코멘트 남겨봤어요.

2020-03-07 13:39 UTC, tramyu commented on src/main/java/com/codessquad/qna/web/user/UserController.java
>      public String createUser(User user) {
프론트 부분이 html의 form을 이용해서 이렇게 처리된 것 같은데

Post를 통한 요청은 보통 `@RequestBody`를 통해 처리합니다.
시간이 날 때 HTTP POST 요청과 스프링의 `@RequestBody` 어노테이션에 대해 찾아보세요
이 부분을 변경하실 필요는 없습니다~ 시간이 나실때 학습해보세요

2020-03-07 13:39 UTC, tramyu commented on src/main/java/com/codessquad/qna/web/user/UserController.java
> +        if (user == null) {
지금 학습하실 필요는 없고 dto를 활용하거나 하실 때 validation이 필요한 경우 적용해보세요

https://www.baeldung.com/spring-boot-bean-validation

2020-03-07 13:39 UTC, tramyu commented on README.md
> +   - 이벤트 버블링, 이벤트 델리게이션에 대해서 더 공부해야할 필요성을 느꼈습니다.
잘 정리한 건 아닌데.. 제가 예전에 자바스크립트 이벤트 관련해서 정리한 문서에요

도움이 되실 진 모르겠지만 첨부합니다.

https://tramyu.github.io/js/javascript-event/

2020-03-07 13:56 UTC, ksundong commented
@tramyu https://github.com/code-squad/java-qna/pull/176#discussion_r386119643
위 링크에 두 번째 질문에 해당하는 내용이 있습니다! 리뷰해주셔서 감사해요!

그리고 `@JsonIgnore`도 찾아서 사용한 거라 알려주신거는 모르고 있었네요...
DTO에대해서도 한 번 공부해야할 것 같습니다. 감사합니다.

2020-03-07 13:57 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/question/Question.java
> +    @JsonIgnore
감사합니다! 알려주신 키워드들도 가볍게 알아두도록 하겠습니다!
DTO에 대해서도 알아보겠습니다. 감사합니다!

2020-03-07 13:58 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/user/User.java
>      private String userEmail;
앗 호눅스도 말씀하셨어서 고치긴해야겠네요.

2020-03-07 14:00 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/user/User.java
> +    public User(String userId, String userPassword, String userName, String userEmail, String userProfileImage) {
이게 `data.sql` 파일로 기본 데이터를 읽어올 때, 빈 생성자에 `setter`로 값을 할당하는게 아니라 생성자에서 값을 할당시켜줘야해서 `public`으로 선언했는데, `private`으로 한 번 설정해보겠습니다.

2020-03-07 14:01 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/user/User.java
> +        if (!"".equals(newPassword)) {
`StringUtils.isEmpty(newPassword)`로 사용하겠군요..!
적용해보겠습니다!

2020-03-07 14:01 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/user/UserController.java
>      public String createUser(User user) {
넵! 감사합니다!

2020-03-07 14:02 UTC, ksundong commented on src/main/java/com/codessquad/qna/web/user/UserController.java
> +        if (user == null) {
DTO에 대해서 알아보고 알려주신 내용은 읽어보겠습니다!

2020-03-07 14:02 UTC, ksundong commented on README.md
> +   - 이벤트 버블링, 이벤트 델리게이션에 대해서 더 공부해야할 필요성을 느꼈습니다.
감사합니다! 저도 대강 정리했는데 꼭 참고하겠습니다!

2020-03-08 13:35 UTC, honux77 commented on src/main/java/com/codessquad/qna/web/question/Question.java
> +    @JsonIgnore
https://stackoverflow.com/questions/1612334/difference-between-dto-vo-pojo-javabeans

2020-03-08 13:38 UTC, merged