Submit Step4 : 스프링 부트로 QA 게시판 구현 1
code-squad/java-qna pull request #198
Opened 2020-03-10 11:45 UTC by Hyune-c

[Heroku 링크](https://codesquad-qnaboard.herokuapp.com/)

## step4. 로그인 구현

### # step3 Refactoring

- CommonUtils 변경
    - 로직의 명시성 강화를 위해 각 get 메소드에 OrError() 를 추가 ... complete
    - 각 소스에 static import 를 추가 ... complete

### # 기능 구현

- 회원과 질문간의 관계 매핑 및 생성일 추가
    - User와 Question 간의 관계를 매핑한다.   
        - 기존 userId 를 사용하던 방법에서 User 객체로 변경 ... complete
        - hidden input 추가로 userId, id 분리 ... complete
    - Question에 생성일을 추가한다. ... complete

-  질문 상세보기 기능
    - 질문 상세보기 기능 구현 ... complete

-  질문 수정, 삭제 기능 구현
    - PUT(수정), DELETE(삭제) HTTP method를 활용해 수정, 삭제 기능을 구현 ... complete

-  수정/삭제 기능에 대한 보안 처리 및 LocalDateTime 설정
    - Back End 프로그래밍에서 정말 중요한 보안 관련된 기능 구현 ... compelte
    - JPA에서 LocalDateTime을 DB 데이터타입과 제대로 매핑하지 못하는 이슈 해결 ... compelte

- 답변 추가 및 목록 기능 구현
    - 답변 기능을 담당할 Answer를 추가하고, Question, User와 매핑 ... compelete
    - Question에 Answer를 @OneToMany로 매핑. 이와 같이 매핑함으로써 질문 상세보기 화면에서 답변 목록이 동작하는 과정 공유 ... compelete

- QuestionController 중복 코드 제거 리팩토링
    - QuestionController에서 보안 처리를 위해 구현한 중복 코드를 제거 ... compelete
    - 중복을 Exception을 활용한 제거와 Result와 같은 새로운 클래스르 추가해 제거 ... compelete

- 질문 삭제하기 실습(선택)
    - 질문 데이터를 완전히 삭제하는 것이 아니라 데이터의 상태를 삭제 상태(deleted - boolean type)로 변경한다. ... complete
    - 질문을 삭제할 때 답변 또한 삭제해야 하며, 답변의 삭제 또한 삭제 상태(deleted)를 변경한다. ... complete
    - 로그인 사용자와 질문한 사람이 같은 경우 삭제 가능하다. ... complete
    - 답변이 없는 경우 삭제가 가능하다. ... complete
    - 질문자와 답변 글의 모든 답변자 같은 경우 삭제가 가능하다. ... complete
    - 질문자와 답변자가 다른 경우 답변을 삭제할 수 없다. ... complete

### # 질문
- 삭제 로직 중 댓글의 작성자 체크/삭제를 동시에 해야되다보니 answers 를 2번 불러오고 loop 도 2번 도는 형태가 되었습니다.   
    - 1개의 loop 에서 삭제를 처리하게 되면 rollback 이 힘들어 아래와 같은 로직을 선택하였는데 어떻게 하면 개선할 수 있을까요?  
    (혹시 여기에 @Transactional 을 사용하는 것인가요?)
    - answer 의 delete 마다 save 를 하게되면서 DB 접근이 많을 것으로 추정됩니다. 어떻게 줄여야될까요?

```java
Iterator<Answer> answers = getAnswersOrError(answerRepository, question).iterator();

// 댓글 중 작성자와 sessionedUser 가 다른 건이 있는지 체크합니다.
answers.forEachRemaining(answer -> {
  if (!answer.getUser().equals(sessionedUser)) {
    throw new QuestionException(CustomErrorCode.USER_NOT_MATCHED);
  }
});

answers = getAnswersOrError(answerRepository, question).iterator();

// answers 를 다시 불러온 후 삭제를 진행합니다.
answers.forEachRemaining(answer -> {
  answer.delete();
  answerRepository.save(answer);
});
```

2020-03-10 14:59 UTC, honux77 commented
갑자기 생각났는데 complete 하지 말고 마크다운 `[x]` 사용하면 깔끔해요.

2020-03-11 13:01 UTC, wheejuni requested changes
수고 많으셨어요. 
얼마나 수고가 많으셨을지 코드에서 충분히 느껴집니다. 그러나 아쉬운 점도 있었습니다. 
다음 과제 수행때는 아래의 사항에 대해 다시 한 번 고민해 주시면 정말 좋겠습니다. 

- 너무 돌아가지 말자. 새로운 것을 학습하는 것도 중요하지만 아는 범위 안에서 최선의 코드를 짜보는 것도 좋은 연습이 됩니다. 
- 단순하게 생각하자. Django 끝에 악수 둔다는 말이 있죠. 코딩에서도 마찬가집니다. 
- "클린코드" 에 대해 지나치게 "분리" 의 관점에서 접근하지 말자. 때론 기능 단위로 메소드가 비대해지는 것도 필요합니다. *다만....*
    - 그런 경우엔 메소드를 분리할 일이 아니라, 내가 피쳐의 단위를 너무 크게 잡지는 않았는지, 즉 코딩이 아니라 설계의 관점으로 다시 접근해야 해결책을 찾을 수 있습니다.
    - 어떠한 기능을 설계할 때, 한 번에 이것도 하고 저것도 하고 다 해야지! 라고 생각하진 않았는지 처음으로 다시 돌아가서 큰 그림을 점검해야 합니다. 

주저리주저리 코멘트가 길었네요. 
감사합니다~

2020-03-11 13:01 UTC, wheejuni commented on src/main/java/com/codessquad/qna/answer/Answer.java
> +  private boolean deleted;
soft delete 방식을 사용한 이유를 알려주세요. ㅎㅎ

2020-03-11 13:01 UTC, wheejuni commented on src/main/java/com/codessquad/qna/answer/AnswerRepository.java
> +  Iterable<Answer> findByQuestionIdAndDeleted(Long questionId, boolean Deleted);
어차피 결과가 없으면 빈 `List` 가 반환될텐데 굳이 리턴 타입으로 `Iterable` 을 택할 이유는 없어보입니다. 
혹시 제가 알지 못하는 다른 이유가 있을까요.

2020-03-11 13:01 UTC, wheejuni commented on src/main/java/com/codessquad/qna/commons/CommonUtils.java
> +  public static User getSessionedUserOrError(HttpSession session) {
`OrError` 접미사가 필요하다고 생각하지 않습니다.
로직 수행중에 예외를 던지는 메소드들에 이런 작명법을 사용하지 않고요, 그리고 엄밀히 말하면, 이 메소드는 예외를 "던진" 것이지 받으라고 건네준 것이 아니기도 합니다. 
메소드 이름을 다시 고민해주세요.

2020-03-11 13:01 UTC, wheejuni commented on src/main/java/com/codessquad/qna/commons/CommonUtils.java
> +  public static Iterable<Answer> getAnswers(AnswerRepository answerRepository, Question question) {
유틸성 클래스에서 파라미터로 Spring Bean을 받는 것은 어색합니다. 
만약 정말 `AnswerRepository` 에 의존성을 가져야했다면, 이 유틸 클래스 자체를 `@Component` 로 선언하고, 의존성 주입을 받는 것이 맞습니다. 

지금은 단순히 `findBy` 에 그쳤으니 큰 문제가 되지 않았지만, 나중에 수정/생성 로직이 추가된다면 트랜잭션 처리와 관해서 또 어색해질 부분이 생길 수도 있습니다. 

이 메소드 자체를 여기에 두지 말고, 필요한 컨트롤러나 `@Service` 클래스 내에서 수행되도록 수정해주세요. 
아울러 `Utils` 클래스들에는 스프링의 의존성 주입이나 특정 컴포넌트에 의존하지 않아도 되는 로직만 담도록 해 주세요.

2020-03-11 13:01 UTC, wheejuni commented on src/main/java/com/codessquad/qna/question/QuestionController.java
> +    return "redirect:/";
이 블록은 아래의 사항에 착안해 **처음부터 다시** 고민해 주세요. 

- 첫번째 `getAnswers()` 한 시점의 답변들과, 두번째 `getAnswers()` 호출한 시점의 답변 목록이 같다고 볼 수 있을까요? 
- `Question` 이 `Answer` 를 들고 있었다면 훨씬 쉽게 풀 수 있는 문제였을텐데요, 우리가 JPA를 사용하는 이유이기도 합니다. `Question` 에게 너 혹시 질문 작성자와 다른 사람이 쓴 답변 갖고있냐고 물어볼 수는 없었나요.

2020-03-11 13:01 UTC, wheejuni commented on src/main/java/com/codessquad/qna/user/User.java
> +    return Objects.equals(getId(), user.getId()) &&
JPA entity에서 `equals` 에 `@Id` 가 비교대상으로 들어가는 것 다시 고민해주세요.

2020-03-11 13:01 UTC, wheejuni commented on src/main/java/com/codessquad/qna/user/UserController.java
> +    if (originUser.validatePassword(newUser.getOldPassword())) {
`User` 엔티티를 request param으로 통째로 받지 말고,
비밀번호 업데이트를 위한 별도의 DTO를 설계했다면 훨씬 더 쉽게 풀 수 있었을 것 같습니다. 
사실 User 객체에게 `oldPassword` 란 객체의 작동을 위해 의미있는 정보가 아닌데 `@Transient` 까지 써가면서 보관하고 있는 측면이 있죠. 

만약 DTO로 기존 비밀번호를 제출받아 한번 인증 처리를 해보고, 실패하면 거기서 예외를 던지고 실행을 종료시키면 의도한 동작을 모두 할 수 있을 것 같은데요, 어떨까요?

2020-03-11 13:05 UTC, Hyune-c commented on src/main/java/com/codessquad/qna/answer/Answer.java
> +  private boolean deleted;
@wheejuni 
`@Column(nullable = false)`
어.. 이게 soft delete 인가요?
DB 상에 not null 의 의미로 넣은 것인데......

2020-03-11 13:06 UTC, wheejuni commented on src/main/java/com/codessquad/qna/answer/Answer.java
> +  private boolean deleted;
아뇨, 엔티티가 `deleted` 라는 플래그를 들고 있는 것에 대한 질문이었습니다.

2020-03-11 13:08 UTC, Hyune-c commented on src/main/java/com/codessquad/qna/answer/AnswerRepository.java
> +  Iterable<Answer> findByQuestionIdAndDeleted(Long questionId, boolean Deleted);
@wheejuni 
예제에서 이렇게 보여주었고, Answer 목록을 순회할 필요성이 있기에 위와 같이 작성했었습니다.

이부분은 크게 고민하지 않은 것이긴 한데, Iterator 의 형태가 아닌 List 와 같은 Collection 형태로 리턴하는게 좋은 것 일까요?

2020-03-11 13:08 UTC, Hyune-c commented on src/main/java/com/codessquad/qna/answer/Answer.java
> +  private boolean deleted;
@wheejuni 
아하. 문제의 조건에 있어서 사용했습니다.
(제약 조건이 없었다면 만들지 않았었을거 같습니다.)

2020-03-11 13:09 UTC, wheejuni commented on src/main/java/com/codessquad/qna/answer/AnswerRepository.java
> +  Iterable<Answer> findByQuestionIdAndDeleted(Long questionId, boolean Deleted);
헐 `Iterable` 을 쓰는 예제도 있군요. 어떤 취지에서 만들어진 예제인지 짐작은 갑니다만 아직 그렇게 사용할 필요는 없습니다. 
당연히 `List` 와 같은 컬렉션 객체들이 더 풍부한 기능을 제공하므로 가급적 그런 리턴 타입을 취해주는 것이 개발편의성에 도움이 될 겁니다.

2020-03-11 13:10 UTC, wheejuni commented on src/main/java/com/codessquad/qna/answer/Answer.java
> +  private boolean deleted;
죄송합니다;; 제가 출제자의 의도를 파악치 못하고...

2020-03-11 13:11 UTC, Hyune-c commented on src/main/java/com/codessquad/qna/commons/CommonUtils.java
> +  public static User getSessionedUserOrError(HttpSession session) {
@wheejuni 
```java
@GetMapping("/form")
  public String form(HttpSession session) {
    log.info("### form");
    getSessionedUserOrError(session);

    return "/questions/form";
  }
```

이 부분은 정말 많이 고민한거였는데요..
초기에 메소드명을 getSessioned() 로 하고 실제 동작은 안에서 Null error 처리도 하다보니, 위의 코드의 경우 왜 쓰지도 않은 Sessioned 를 get 하는지 로직이 보이지 않았습니다.

그렇다고 동일한 동작을 하는 checkLogin() 같은 메소드를 같이 만들기는 뭐해서, 절충안으로 나온게 저 형태였습니다.

혹시 위와 같은 고민일때는 어떻게 해야 될까요?

2020-03-11 13:15 UTC, wheejuni commented on src/main/java/com/codessquad/qna/commons/CommonUtils.java
> +  public static User getSessionedUserOrError(HttpSession session) {
메소드의 호출을 통해 무엇을 받고싶은지만 집중하면 됩니다. 
`getSessionedUser()` 를 호출하는 이유는 명백하게 `sessionedUser` 를 받고자 하는 거니까 거기에만 집중하면 됩니다. 

메소드가 할 일을 잘 보여주는 이름이면 충분합니다.

2020-03-11 13:16 UTC, Hyune-c commented on src/main/java/com/codessquad/qna/commons/CommonUtils.java
> +  public static Iterable<Answer> getAnswers(AnswerRepository answerRepository, Question question) {
@wheejuni 
이건 이전에 질문을 하고 honux 에게도 질문을 드렸지만 딱히 개선방법이 보이지 않아서 이렇게 했었습니다.
아직 `@Service` 에 대한 개념이 미숙해서 어떻게 개선해야 될지 잘 감이 안오는데.. 조금 더 공부해보겠습니다. ㅠ

### # 질문
- 여러 곳에서 쓰일 수 있는 메소드를 CommonUtils 로 모으다 보니 DB 에 접근할 때가 애매해졌습니다.  
    - 아래 메소드는 static 이며 Repository 를 매개변수로 전달받게 만들었습니다.
    - Repository 는 Singleton 이기에 전역에서 접근하려 했는데 @autowired 는 static 적용을 할 수가 없었습니다.
    - 어쩔 수 없이 매개변수로 전달하는 형태로 구현했는데 의존성 면에서 좋아보이지 않아 고민됩니다.  

```java
public static Question getQuestion(QuestionRepository questionRepository, Long id) {
```

2020-03-11 13:18 UTC, Hyune-c commented on src/main/java/com/codessquad/qna/commons/CommonUtils.java
> +  public static User getSessionedUserOrError(HttpSession session) {
@wheejuni 
답변을 잘 이해하지 못했습니다..

그렇다면 위처럼 login 여부만 체크하려고 할 때는, 이미 같은 동작을 가진 메소드가 있더라도 (이름이 다른) 명시적인 이름을 가진 메소드를 다시 만들어주는 것이 좋다는 건가요?

2020-03-11 13:18 UTC, wheejuni commented on src/main/java/com/codessquad/qna/commons/CommonUtils.java
> +  public static Iterable<Answer> getAnswers(AnswerRepository answerRepository, Question question) {
"모아야 한다" 라는 방법을 정해놓고 고민한 것은 아닐까요? ㅠㅠ

2020-03-11 13:19 UTC, Hyune-c commented on src/main/java/com/codessquad/qna/user/UserController.java
> +    if (originUser.validatePassword(newUser.getOldPassword())) {
@wheejuni 
생각해보지 못한 부분이었습니다.
참고하여 리팩토링 해보겠습니다!

2020-03-11 13:20 UTC, Hyune-c commented on src/main/java/com/codessquad/qna/user/User.java
> +    return Objects.equals(getId(), user.getId()) &&
@wheejuni 
혹시 왜 일까요..? id 는 DB 상에 unique 하게 생성되는 값이기에 정확한 비교를 할 수 있는 대상이라고 생각했었습니다.

2020-03-11 13:21 UTC, wheejuni commented on src/main/java/com/codessquad/qna/commons/CommonUtils.java
> +  public static User getSessionedUserOrError(HttpSession session) {
제가 보기에 `getSessionedUser`와 `checkLogin` 은 완전히 다른 동작인데요.
`HttpSession` 에 어떤 형태로든 유저가 담겨있으면 로그인이 돼 있다고 보고싶은 건가요? 
그렇다면 `checkLogin` 을 따로 만들고 `checkLogin` 에서 `getSessionedUser`를 호출해도 좋고요. 
그리고 두 메소드는 리턴 타입이 분명히 다를텐데(제가 생각하기로는 `checkLogin`은 `boolean` 을 리턴할 겁니다) 같은 동작이라고 보기는 살짝 어렵지 않을까요.

2020-03-11 13:21 UTC, Hyune-c commented on src/main/java/com/codessquad/qna/question/QuestionController.java
> +    return "redirect:/";
@wheejuni 
아...... 역시 한번의 loop 에서 처리해야됬는데.. 
감사합니다!

2020-03-11 13:22 UTC, wheejuni commented on src/main/java/com/codessquad/qna/user/User.java
> +    return Objects.equals(getId(), user.getId()) &&
`@Id` 가 부여되는 시점이 언제일까요? 
영속성 컨텍스트가 부여해줄때까지 기다려야 할 텐데요. 
Repository에 save하기 전에 두 객체를 비교할 일은 전혀 없을까요.

2020-03-11 13:22 UTC, Hyune-c commented on src/main/java/com/codessquad/qna/commons/CommonUtils.java
> +  public static User getSessionedUserOrError(HttpSession session) {
@wheejuni 
말씀해주신 방식이 이치에 맞는 것 같습니다. 
리팩토링에 참고하겠습니다!

2020-03-11 13:24 UTC, Hyune-c commented on src/main/java/com/codessquad/qna/commons/CommonUtils.java
> +  public static Iterable<Answer> getAnswers(AnswerRepository answerRepository, Question question) {
@wheejuni
솔직히 아직 어떻게 개선해야 될지 방법이 떠오르지 않습니다...
리팩토링 방법이 생각난 다른 부분을 먼저 고치고 고려해보겠습니다 ㅠ

2020-03-11 13:26 UTC, Hyune-c commented on src/main/java/com/codessquad/qna/user/User.java
> +    return Objects.equals(getId(), user.getId()) &&
@wheejuni 
이 부분은 전혀 고려하지 못한 부분이었습니다. 좀 더 생각해보겠습니다.

2020-03-11 13:31 UTC, wheejuni commented on src/main/java/com/codessquad/qna/user/User.java
> +    return Objects.equals(getId(), user.getId()) &&
unique 라는 키워드를 사용하셨기에 고민할 거리 하나 추가해 드릴게요. ㅎㅎ;; 
unique에도 사실은 레벨이 있습니다. 
DBMS 레벨에서 unique할 수도 있고, JVM 레벨에서 unique할 수도 있습니다. 
다시 말하면, DB에서 unique한 값이 JVM에선 unique하지 않을 수도 있고, 거꾸로의 경우도 가능하겠죠. 
쉽게 말해 "우물 안 개구리" 같은 상황인 겁니다. 우물 바깥에 어떤 값들이 있는지 모르니까 스스로는 unique하다고 생각하겠지만 사실 우물 밖에선 흔한 값이였을 수도 있죠. 

JVM환경에서 개발하며 정말 unique한 값을 사용하는 것이 필요하다면 [UUID](https://docs.oracle.com/javase/7/docs/api/java/util/UUID.html) 에 대해 알아야 할 겁니다. 
너무 깊게 공부하지는 마시고;; 그냥 재미삼아 한 번 찾아보세요. 

unique라는 키워드를 언급하신 것이 뭔가 걱정(?) 되어 코멘트 남겨봅니다.

2020-03-12 14:44 UTC, merged

2020-03-12 14:50 UTC, honux77 commented
![DanTheMan](https://user-images.githubusercontent.com/2168702/76533959-34c24e80-64bc-11ea-8f16-7c24b7fad4f9.png)