[Sigrid] Step3 미션 완료
code-squad/java-qna pull request #199
Opened 2020-03-10 12:01 UTC by jypthemiracle

## [Sigrid] Step3 미션 완료
### 완료한 요구사항
* 로그인 기능
* 로그인 상태에 따른 메뉴 처리, 보안 처리 및 로그아웃 기능
* 자기 자신의 정보만 수정할 수 있도록 보안 처리
* 질문하기, 질문 수정하기, 질문 삭제하기, 질문 목록 기능
* 답변하기, 답변 수정하기, 답변 삭제하기, 답변 목록 기능
* User, Question @ManyToOne 연결
* Posts, Answers @OneToMany 연결
* 질문하기, 질문 수정하기, 질문 삭제하기 API 테스트 코드 구현
* 로그인 계정 정보가 사전에 담긴 SQL 테스트 데이터 추가

### 구현하면서 의문이 들었던 사항
* Posts와 Answers를 저장할 때 author 정보가 DTO에는 담기지만 최종 객체에는 담기지 않는 현상
	* PostsSaveRequestDto와 AnswersSaveRequestDto는 각각 Posts와 Answers를 저장하기 위한 DTO이다. 여기서 작성자 정보를 가져오기 위해 SpringContext를 거쳐 HttpSession에 접근한다.
	* DTO에서는 author이 정보를 잘 가져와 User의 객체를 정상적으로 저장했다. 하지만 해당 DTO를 저장 기능이 있는 API로 전송하는 순간 author 객체가 누락되어 null 값으로 뽑히는 오류가 발생했다.
	* 이는 자바 객체를 JSON으로 변환하지 못해 발생하는 문제로 보인다. Dion(@ksundong)님이 Posts와 Answers에 serialize를 implement해보라는 조언이 있었으나 해당 시도는 실패했다.
	* 일단 문제를 해결하기 위해 Posts와 Answers 객체 자체에서 세션에 접근하여 사용자 정보를 가져오도록 하였다.
	* 해당 문제에 대해 다음 스텝에 대해 깊이 있게 고민해보고 자바 객체를 JSON 형식으로 변환하는 라이브러리의 사용법에 대해 찾아볼 예정이다.
	* 다만, DTO는 일종의 POJO여야 한다는 점에서 DTO 자체가 세션에 접근해서 사용자 정보를 가져오는 등의 능동적인 기능을 수행하는 것이 객체지향의 관점에서 어긋나는 것이라고 생각이 든다. 리뷰어님의 의견이 궁금하다.
* 페이지 뷰에서 ```isDeleted()``` 처리가 되어 지워진 Posts를 구별하기 위한 시도에 대하여
	* 해당 스텝에서 기능을 구현하기 위하여 ArrayList를 활용하여 미삭제 및 삭제의 모든 글이 담겨있는 리스트 타입의 ```getAnswers()```를 선언하고자 했으나 OneToMany를 활용할 수 없다고 한다.
	* 또는 ```getAnswers()``` 자체에서 ```isDeleted() == false``` 인 Posts만 가져오고자 하였으나 ```'Basic' attribute type should not be a container``` 오류가 발생한다.
	* 이번 스텝에서는 기능을 구현하기 위해 전체 글의 리스트인 ```answers``` 에서 원소를 가져와 새로운 ArrayList를 선언한 다음 원소의 ```isDeleted()``` 여부가 ```false``` 인 친구들만 해당 ArrayList에 넣어두고 이를 리턴하도록 구현했다.
	* 이것이 객체지향의 관점에서 최선의 방법인지 궁금하다. 이러한 접근은 Answers가 아니라 Service 같은 곳에서 역할을 해야 하는 것이 아닌가 의문이 강하게 들고 있다.

### 다음 스텝에서 구현할 사항
> 주로 리팩토링에 집중할 예정입니다. 리뷰어님께서는 혹시 리팩토링 할 만한 부분을 지적해주시면 정말 감사드리겠습니다. ^^
* Controller 중복 코드 줄이기
* Result 클래스의 도입
* @Query 어노테이션을 활용하지 않고 다른 spring data query methods 방법 학습해보기
* Service 에서 Update 또는 Save 수행 이후 객체 자체를 꺼내도록 구조 변경하기
* Posts와 Answers를 저장할 때 객체 자체에서 세션에 접근하여 사용자 정보를 가져오지 않고, 자바 객체 자체를 JSON에 담아서 전송해보는 경험 얻기
* 로깅 라이브러리 사용하기

### Remark
* 이번 스텝에서는 개념 학습보다는 Step3가 요구하는 기능을 구현하는 데 많은 시간과 노력을 기울였다.
* 다음 스텝의 요구사항은 이미 구현하였으므로, 지난 PR과 이번 PR에서 이루어 진(또는 이루어 질) 리뷰어님의 코드 리뷰를 바탕으로 테스트 커버리지를 넓히고 리팩토링을 하는 데 시간을 쏟을 예정이다.
* 너무 배보다 배꼽이 큰 것이 아닌가 하는 생각을 하고 있지만, 일단 학습의 과정이니 무리하지 않고 여유 있게 진행해볼 생각이다.

2020-03-10 14:34 UTC, ksundong commented
왜 메일이 왔나 했더니 제가 멘션되었군요 ㅋㅋㅋㅋㅋㅋ

2020-03-11 00:35 UTC, jypthemiracle commented
사용자가 두 명 이상일 때 간헐적으로 자신의 댓글을 수정하려고 하면 잘못된 접근이라는 페이지로 이동되는 버그를 발견했다.

2020-03-13 12:58 UTC, wheejuni requested changes
과제 진행하시느라 고생 많으셨습니다. 
그러나 너무 많은 경우의 수를 고려했고, 지나치게 다양한 시도에 집착하셨다는 아쉬움도 듭니다. 

조금만 힘을 빼고 쉽게 생각해 주세요.
제가 많은 코멘트 달아드렸는데요, 생각해 보시고, 만약 저와 생각이 다르신 부분이 있다면 이곳에 대댓이나 자바 슬랙채널에서 함께 얘기 나눠보시죠.

2020-03-13 12:58 UTC, wheejuni commented on src/main/java/com/codessquad/qna/domain/Answers.java
> +public class Answers extends BaseTimeEntity {
일반적으로 클래스 이름으로 복수형은 사용하지 않습니다.

2020-03-13 12:58 UTC, wheejuni commented on src/main/java/com/codessquad/qna/domain/Answers.java
> +      PostsRepository postsRepository = SpringContext.getBean(PostsRepository.class);
Domain 엔티티에서 스프링 컴포넌트에 대한 의존 관계를 갖는 것은 **절대 금지입니다.**
다시 한 번 강조합니다. **절대 금지입니다.**
**절대 금지입니다. 반드시 수정해주세요.** 

서비스 클래스에서 `@Transactional` 블록으로 묶어놓고 객체를 넘겨서 의존 관계를 갖게 하거나,
`cascade` 옵션을 적용하거나, 여하간 엔티티가 스프링에 대해 전혀 모르게 다시 구현하세요.

2020-03-13 12:58 UTC, wheejuni commented on src/main/java/com/codessquad/qna/domain/Posts.java
> +  @OrderBy("Id asc")
꼭 쿼리로써 정렬해야 할까요?

2020-03-13 12:58 UTC, wheejuni commented on src/main/java/com/codessquad/qna/domain/Posts.java
> +  public ArrayList<Answers> getUndeletedAnswers() {
메소드는 상위 컬렉션 인터페이스를 리턴 타입으로 갖도록 수정해주세요.

2020-03-13 12:58 UTC, wheejuni commented on src/main/java/com/codessquad/qna/domain/Posts.java
> +  public Posts(Users author, String title, String content) {
생성자는 메소드의 최상단에 위치하게 해 주세요.

2020-03-13 12:58 UTC, wheejuni commented on src/main/java/com/codessquad/qna/domain/Posts.java
> +      return attr.getRequest().getSession(true);
이게 왜 `PostsBuilder` 에 위치해야할까요?

2020-03-13 12:58 UTC, wheejuni commented on src/main/java/com/codessquad/qna/domain/Posts.java
> +    public Posts.PostsBuilder author() { //Posts 클래스 내부의 PostsBuilder 라는 의미
아하. 여기서 이렇게 사용하기 위해 만든 거군요. 
그런데 `builder()` 의 기능에 다소 벗어나는 방향인 것 같은데, `User` 를 파라미터로 받는 방법은 어땠을지 다시 한 번 돌아가서 생각해보시면 좋겠어요. 
도메인 엔티티가 여기저기 찌르고 다니는 것은 아주 좋지 않고요, 리팩토링 용이성을 크게 저해하는 요소가 됩니다.

2020-03-13 12:58 UTC, wheejuni commented on src/main/java/com/codessquad/qna/domain/Posts.java
> +    }
`toString()` 을 구현하려면 `@Override` 를 명시적으로 붙여줘서 `java.lang.Object` 의 기능으로서 `toString()` 을 구성했다고 말해줍시다.
그런데 빌더에 정말 `toString()` 이 필요한가요???

2020-03-13 12:58 UTC, wheejuni commented on src/main/java/com/codessquad/qna/domain/Users.java
>    @Id
필드 이름은 소문자로 시작합시다.

2020-03-13 12:58 UTC, wheejuni commented on src/main/java/com/codessquad/qna/domain/Users.java
> +  }
빈 브라켓은 한 줄에 열고 닫아도 됩니다.

2020-03-13 12:58 UTC, wheejuni commented on src/main/java/com/codessquad/qna/domain/Users.java
> +  public boolean matchId(Long newId) {
`newId` 라고 해서 아이디 값을 교체하는 줄 알았습니다.

2020-03-13 12:58 UTC, wheejuni commented on src/main/java/com/codessquad/qna/domain/Users.java
> +  public boolean matchPassword(String newPassword) {
위 메소드에도 공통 적용되는 사항인데, `boolean` 리턴하는 메소드에 대해서 접두사를 다시 고민해주세요.

2020-03-13 12:58 UTC, wheejuni commented on src/main/java/com/codessquad/qna/service/answers/AnswersService.java
> +  public Long save(AnswersSaveRequestDto requestDto) {
지난번에도 비슷한 역할을 하는 메소드의 리턴 타입에 대해 한 번 말씀드린 적이 있었는데 잘 동의가 되시지 않는 것 같네요. 
저도 `Long` 을 리턴하는 것에 동의하지 못하기에 한번만 더 제 의견을 밝혀 드릴게요. 
받아들이신다면 감사하고요, 받아들이지 않으셔도 좋습니다. 그러나 한 번만 더 말씀드리고 싶어서 ㅠㅠ 코멘트 달아봅니다. 

우선 메소드 안에서 온전하게 처리된 객체에 대해 **특정 필드만 리턴해야 할 이유가 안 보입니다.**
만약 사용처에서 ID값이 필요하다면, 우선 온전한 객체를 전달받고 거기서 getter를 호출하거나 그 객체에게 몰어보면 그만입니다. 
해당 도메인 엔티티를 처리하기 위해 작성한 서비스 클래스에서 해당 엔티티와 무관한 리턴 타입을 갖는 메소드를 구현하는 것은 어떻게 봐도 어색합니다. 

제 논리가 수긍이 가신다면 앞으로 다른 리턴 타입을 사용하시는 것을 고민해보시고, 만약 수긍이 되지 않으신다면, 
앞으로 이 부분에 대해선 리뷰하지 않겠습니다.

2020-03-13 12:58 UTC, wheejuni commented on src/main/java/com/codessquad/qna/service/answers/AnswersService.java
> +  public Long save(AnswersSaveRequestDto requestDto) {
https://github.com/code-squad/java-qna/pull/172/files#r385954818 우리는 이런 대화를 나눴었네요.

2020-03-13 12:58 UTC, wheejuni commented on src/main/java/com/codessquad/qna/web/dto/posts/PostsSaveRequestDto.java
> +    public PostsSaveRequestDto.PostsSaveRequestDtoBuilder author(HttpSession httpSession) {
`User` 클래스를 바로 받는 것으로 수정해주세요.

2020-03-13 12:58 UTC, wheejuni commented on src/main/java/com/codessquad/qna/controller/answers/AnswersRepository.java
> +  @Query("SELECT p FROM Answers p where p.Id = :Id AND p.deleteStatus = false")
Query method 자체로 구현할 수 있었습니다. 
그런 방향으로 수정할 수 있을지 한번만 더 고민해주세요.

2020-03-13 12:58 UTC, wheejuni commented on src/main/java/com/codessquad/qna/domain/Answers.java
> +  @OnDelete(action = OnDeleteAction.CASCADE)
지울때만 영속성이 전이되면 되나요? 생성과 함께 전이될 가능성은 없었나요?

2020-03-13 14:15 UTC, jypthemiracle commented on src/main/java/com/codessquad/qna/service/answers/AnswersService.java
> +  public Long save(AnswersSaveRequestDto requestDto) {
아 해당 부분은 제가 위의 PR 설명에도 적어두었는데 제가 기능 구현을 목표로 하다보니 해당 부분에 대한 고민을 하지 않았습니다. 다음 스텝에서 충분히 고민하고 다시 의견을 나누길 희망합니다.

2020-03-13 14:21 UTC, jypthemiracle commented on src/main/java/com/codessquad/qna/domain/Answers.java
> +      PostsRepository postsRepository = SpringContext.getBean(PostsRepository.class);
저도 Domain 엔티티에서 스프링 빈을 가져오는 방식을 구현을 위해 어쩔 수 없이 택했지만, 논리적으로 이상하게 보였습니다. 해당 부분을 어떻게 수정하면 좋을 지 더 고민해보도록 하겠습니다.

2020-03-14 03:09 UTC, honux77 commented on src/main/java/com/codessquad/qna/service/answers/AnswersService.java
> +  public Long save(AnswersSaveRequestDto requestDto) {
제가 보기에는 크게 고민할 부분은 아니고 객체 전체를 리턴하는 게 베스트 프랙티스입니다. JPA save() 도 같은 방식으로 동작하고 그 외에 대부분의 유사한 프레임워크 / 라이브러리들은 항상 객체 전체를 리턴합니다.

2020-03-14 03:11 UTC, honux77 commented on src/main/java/com/codessquad/qna/domain/Answers.java
> +  @OnDelete(action = OnDeleteAction.CASCADE)
on delete cascade 적용한 거 좋아요.
보통 실제 서비스라면 댓글이 달린 질문은 삭제가 불가능한 경우가 많으니 그것도 생각해 보세요.

2020-03-14 03:12 UTC, honux77 commented
수고하셨어요. 많은 고민은 한 것도 잘했고, 잘 짰어요. 다음 단계에서는 코멘트 잘 반영하고 조금씩 개선해 보세요.

2020-03-14 03:12 UTC, merged