[Han] Step6 Pull request
code-squad/java-qna pull request #204
Opened 2020-03-11 08:34 UTC by 102092

1. 요구사항
- 페이징 기능 (페이지당 15개씩, 페이지 카운트 5개, 생성일 내림기준) 
--> 페이지당 4개 게시물, 페이지 카운트 5개로 설정하여 구현

2. 질문사항
- 처음에는, 프론트에서 페이징 기능을 구현하려다 실패하여.. PageUtil 객체를 생성하여, currentPage를 기준으로 페이지 리스트를 생성하는 방식으로 만들어보려고 하였습니다. 
보통 페이징 기능은 어떤 것(총 게시물 갯수, 페이지 갯수등) 을 기준으로 만들어지는지 궁금합니다..

감사합니다.

2020-03-12 14:53 UTC, honux77 commented
페이징의 기준은 보통 페이지당 게시물의 갯수를 기준으로 만들어집니다. 
예를 들어 페이지당 20개 기준이고 게시물이 50개면 세 페이지가 나오겠네요. 요즘은 서버에서 API를 제공해 주고 프론트에서 리엑트 같은 것을 이용해서 렌더링합니다. 

백엔드 API는 성능상 유리하기 위해서 DB에서 빠르게 접근하고 작은 양의 데이터를 보내 주는 것을 선호합니다.

2020-03-13 12:49 UTC, tramyu commented
> 보통 페이징 기능은 어떤 것(총 게시물 갯수, 페이지 갯수등) 을 기준으로 만들어지는지 궁금합니다..

페이징 기능은 Spring에서 구현해둔 `PageImpl`같은 객체들을 참고해보시면 좋을 것 같습니다.
이미 기능이 많이 들어있어서 추가로 구현하기보단 사용하는게 더 편리했던 것 같아요.

2020-03-13 12:49 UTC, kyucumber requested changes

2020-03-13 12:49 UTC, tramyu commented on src/main/java/com/codessquad/qna/controller/PageController.java
> +  public String index(Model model, Optional<Integer> page) {
Optional<Integer> page로 받으신 이유가 있을까요?
저도 페이징을 자주 해보진 않았지만, 컨트롤러의 파라미터로 Optional을 사용하는 것도 일반적이지 않은 패턴으로 보입니다.
`@PageableDefault`, `Pageable` 관련해서 찾아보세요.

```suggestion
  public String index(Model model, Pageable pageable) {
```

그리고 Optional 관련해서 문서를 첨부했는데, 6번의 내용을 한번 참고해보세요.

http://homoefficio.github.io/2019/10/03/Java-Optional-%EB%B0%94%EB%A5%B4%EA%B2%8C-%EC%93%B0%EA%B8%B0/

2020-03-13 12:49 UTC, tramyu commented on src/main/java/com/codessquad/qna/controller/PageController.java
> +    int pageNumber = page.isPresent() ? page.get() - 1 : 0;
Optional을 파라미터로 활용하지 않았으면 좋겠지만, 사용한다면 isPresent 대신 `.orElse` 등을 활용하는 방법도 있을 것 같네요.

2020-03-13 12:49 UTC, tramyu commented on src/main/java/com/codessquad/qna/web/PageUtil.java
> +public class PageUtil {
이름은 Util인데, 역할 자체는 뭔가 페이지의 상태를 저장하고 하는 기능이 들어가있네요

2020-03-13 12:49 UTC, tramyu commented on src/main/java/com/codessquad/qna/web/PageUtil.java
> +public class PageUtil {
추가로, Spring에서 제공하는 `PageImpl`같은 클래스들을 활용할수도 있어요

```java

/**
 * Basic {@code Page} implementation.
 *
 * @param <T> the type of which the page consists.
 * @author Oliver Gierke
 * @author Mark Paluch
 */
public class PageImpl<T> extends Chunk<T> implements Page<T> {

	private static final long serialVersionUID = 867755909294344406L;

	private final long total;

	/**
	 * Constructor of {@code PageImpl}.
	 *
	 * @param content the content of this page, must not be {@literal null}.
	 * @param pageable the paging information, must not be {@literal null}.
	 * @param total the total amount of items available. The total might be adapted considering the length of the content
	 *          given, if it is going to be the content of the last page. This is in place to mitigate inconsistencies.
	 */
	public PageImpl(List<T> content, Pageable pageable, long total) {

		super(content, pageable);

		this.total = pageable.toOptional().filter(it -> !content.isEmpty())//
				.filter(it -> it.getOffset() + it.getPageSize() > total)//
				.map(it -> it.getOffset() + content.size())//
				.orElse(total);
	}
    // ...
}
```

2020-03-13 12:49 UTC, tramyu commented on src/main/resources/data.sql
> +INSERT INTO QUESTION (id, created_time, modified_time, contents, title,count_of_answer, writer_id) VALUES (29, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '페이지테스트27', '페이지테스트27',0, 1);
data.sql에 중복되는 값들이 많이 들어가네요, 이렇게 정의해도 크게 상관없지만 CommandLineRunner와 같은 걸 이용해 코드 안에서 동적으로도 정의할 수 있을 것 같아요.

2020-03-14 03:19 UTC, honux77 commented on src/main/resources/data.sql
> +INSERT INTO QUESTION (id, created_time, modified_time, contents, title,count_of_answer, writer_id) VALUES (29, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '페이지테스트27', '페이지테스트27',0, 1);
저도 한번은 커맨드 라인 러너로 구현하고, 다음 번에는 sql 생성 프로그램을 따로 짜서 sql문으로 넣는 방식으로 구현했었어요. 간단한 건 CommandLineRunner도 괜찮을 듯.

2020-03-14 03:21 UTC, honux77 commented
https://docs.spring.io/spring-data/jpa/docs/current/api/org/springframework/data/jpa/repository/JpaRepository.html

보면 
 ```
public interface JpaRepository<T,ID>
extends PagingAndSortingRepository<T,ID>, QueryByExampleExecutor<T>
```
PagingAndSortingRepository 가 나와 있는데 이 클래스가 페이징을 쉽게 할 수 있게 도와줍니다. 
참고하세요. 

이전 단계 강의자료에도 나와 있어요.

2020-03-14 03:22 UTC, merged

2020-03-14 03:22 UTC, honux77 commented
수고하셨어요! 잘하고 있는 듯!

2020-03-16 14:05 UTC, 102092 commented on src/main/java/com/codessquad/qna/controller/PageController.java
> +  public String index(Model model, Optional<Integer> page) {
@tramyu 새로운것을 알았네요! 감사합니다 !!