[Henry] step5
code-squad/java-qna pull request #207
Opened 2020-03-12 12:42 UTC by wooody92

### 0. 구현 기능

- 답변 추가하기 (ajax, json 활용)
  - Template 생성 및 append 메서드를 통해 오름차순으로 정렬
- 답변 삭제하기 (ajax, json 활용)
  - answer 객체의 boolean deleted 값을 받아 이벤트 발생시킨 템플릿 삭제
- 답변 수정하기
  - 수정하기 버튼 클릭 시, 서버로부터 json data 정상적으로 받아오는 것을 확인했다. 코드 작성하면서 생각해보니 댓글 수정기능의 경우는 댓글 수정폼이라는 새페이지로 로드해서 수정하는 방식이어서 ModelAndView 이용하여 처리했다.
- @JsonIgnore 사용하여 양방향 연관관계 무한참조 에러제거
- 로깅 라이브러리 log4j2 -> logback 변경

### 1. 회고

- Ajax, jQuery, XHR 등 처음 접해서 개념을 학습했다.

  https://github.com/wooody92/notes/tree/master/spring/study

- 프로젝트 진행하며 실수 혹은 무지로 인해 삽질한 내용을 정리했다.

  https://github.com/wooody92/notes/tree/master/spring/삽질노트

- GitHub 블로그를 만들어 정리해나가면 좋을 것 같다고 생각했다.

2020-03-15 11:55 UTC, tramyu commented
> 아래 처럼 구분하여 사용하는 것이 좋을까요? 아니면 위 처럼 ModelAndView를 사용해서 하나의 클래스로 사용해도 상관이 없나요?

```
@RestController를 사용하여 객체 데이터만을 반환하는 ApiAnswerController
@controller를 사용하여 view page만 반화하는 AnswerController
```

ModelAndView를 명시적으로 리턴해도 무방하겠지만.. `@RestController`라는 어노테이션의 의미와는 잘 맞지 않는 것 같아서 분리하는게 좋을 것 같아요.
그리고 `ModelAndView`를 리턴하는 방식 또한 최근에 잘 사용하지 않는 것 같아서 분리하시는게 좋을 것 같습니다.

2020-03-15 11:55 UTC, kyucumber requested changes

2020-03-15 11:55 UTC, tramyu commented on src/main/java/com/codessquad/qna/Answer.java
> +    @JsonProperty
Entity에 Json 관련된 어노테이션들을 다 넣으셨네요, 아직 학습하지 않으셨겠지만 엔티티를 직접 Presentation layer(Controller)에 노출시키기 보다는 `dto`를 활용하시는게 좋습니다.

위에 적으신 것 처럼 양방향 연관관계의 순환 참조 문제라거나, 추후 Lazy로 정의된 자식 엔티티들에 대해 예외가 발생할 수 있어요(Lazy로 걸린 엔티티를 open session in view를 끄고 사용하면 `LazyInitializationException`와 같은 예외를 자주 볼 수 있습니다.)

지금 단계에서 깊게 학습하실 필요는 없을 것 같고 이런 키워드들이 있구나, 하고 넘어가시면 될 듯 합니다.
궁금하시면 open session in view와 관련된 내용은 https://kingbbode.tistory.com/27 용근님의 블로그에 잘 정리되어 있으니 가볍게 읽어보세요

2020-03-15 11:55 UTC, tramyu commented on src/main/java/com/codessquad/qna/Question.java
> +    @JsonIgnore
`@JsonIgnore`를 이용해 양방향 순환 참조 문제를 해결하셨네요 다른 방법도 있어요 `@JsonIgnore`가 더 간단해서 굳이 변경하실 필요는 없습니다.

`@JsonManagedReference`, `@JsonBackReference`

관련 문서 아래 첨부합니다.


https://www.baeldung.com/jackson-bidirectional-relationships-and-infinite-recursion

2020-03-15 11:55 UTC, tramyu commented on src/main/java/com/codessquad/qna/Question.java
>      public Question() {}
JPA에서 default constructor가 필요해 정의하신 것 같네요 
`protected`로 정의해 기본 생성자를 넓은 범위에 노출하지 않는게 좋을 것 같아요.

Lazy로 걸리는 엔티티라면 `protected`, 그게 아니라면 `private`으로 선언해도 되는걸로 기억하고 있어요(`private`이어도 JPA 내부적으로 Reflection 등을 활용하기 때문에 생성이 가능합니다.)

통일성을 위해 `protected`로 정의하시는걸 추천드립니다.

2020-03-15 11:55 UTC, tramyu commented on src/main/java/com/codessquad/qna/QuestionController.java
>          } catch (EntityNotFoundException e) {
`EntityNotFoundException`에 대한 catch가 중복해서 잡히고 있네요
`@ControllerAdvice` 등으로 중복을 제거해볼수도 있을 것 같아요

```java
@ControllerAdvice
public class ControllerAdviceExample {
    @ExceptionHandler(EntityNotFoundException.class)
    public String handleEntityNotFound(HttpServletRequest req, Exception ex) {
        // ...
    }
}
```

2020-03-15 11:57 UTC, tramyu commented on src/main/java/com/codessquad/qna/Answer.java
>      private boolean deleted;
Soft delete 방식으로 사용하실거면 Entity에도 `@Where`과 같은 어노테이션의 추가가 필요해보입니다.

2020-03-15 11:59 UTC, tramyu commented on src/main/java/com/codessquad/qna/User.java
> +    @JsonProperty
json 이름을 재정의 할 경우가 아니라면 굳이 하나씩 `@JsonProperty` 어노테이션을 붙여주지 않아도 괜찮을 것 같네요

2020-03-15 14:21 UTC, honux77 commented on src/main/java/com/codessquad/qna/Question.java
> +    @JsonIgnore
요즘 검색만 하면 다 바엘둥(?) 닷컴이 나오네요. 신기신기

2020-03-15 14:27 UTC, merged

2020-03-20 07:44 UTC, wooody92 commented on src/main/java/com/codessquad/qna/User.java
> +    @JsonProperty
네 getter를 사용하고, 불필요한 @JsonProperty 제거했습니다~

2020-03-20 07:59 UTC, wooody92 commented on src/main/java/com/codessquad/qna/QuestionController.java
>          } catch (EntityNotFoundException e) {
@ExceptionHandler보다 상위 개념이군요. 예외처리가 어렵네요 ㅠ 조언 감사합니다.

2020-03-22 15:13 UTC, wooody92 commented on src/main/java/com/codessquad/qna/Answer.java
> +    @JsonProperty
아직 JPA에 대한 이해가 부족해서 어노테이션같은 기능들을 사용하면 어떤식으로 돌아가는건지 와닿지 않아서 어렵네요 ㅜㅜ 용어적인 부분부터 공부하면서 해결해 나가야겠네요. 리뷰 감사합니다~!