Submit Step6 : 스프링 부트로 QA 게시판 구현 2
code-squad/java-qna pull request #212
Opened 2020-03-14 15:07 UTC by Hyune-c

[Heroku 링크](https://codesquad-qnaboard.herokuapp.com/)

## step5. XHR과 AJAX

### # 기능 구현

- [x] AJAX로 답변 추가 기능 구현
- [x] AJAX로 답변 삭제 기능 구현 
- [x] 답변 삭제 기능 버그 해결 

## step 6. 페이지 나누기

### # step4 refactoring 
- [x] Iterator 의 형태보다는 Collection 의 형태를 가지도록 수정 
- [x] orError() 메소드명에 대한 개선
- [x] checkLoginOrError() 메소드 추가
- [x] Question 삭제 시 Answer 삭제 로직에 대한 개선
- [x] oldPassword 사용에 대한 개선 
    - update form 의 input tag 에서 바로 가져오기 위함으로 유지합니다.
- [ ] Bean 의 Equal() 오버라이딩시 id 값의 비교 개선
    - 개선 방법을 찾지 못해 다음 step 으로 넘깁니다.
- [ ] 매개변수로 Bean 넣지 않기 
    - 개선 방법을 찾지 못해 다음 step 으로 넘깁니다.

### # 기능 구현

- [x] 질문을 한 페이지에 15개씩 가져오도록 구현합니다.
- [x] 질문 목록은 생성일 기준 내림 차순으로 구현합니다.
    - 최종 수정일을 기준으로 정렬하였습니다.
- [x] 1을 누르면 가장 최근에 쓴 질문 15개가 보이고, 2를 누르면 16번째부터 30번까지의 글이 보여야 한다.
- [x] 한 화면에 보이는 페이지 수는 최대 5개이다. 6개 넘어가는 경우 다음 페이지 그룹으로 이동할 수 있는 버튼이 나타나야 한다.
- [x] 예를 들어 총 페이지 수가 8인 경우 다음 페이지 그룹으로 이동하면 6, 7, 8 페이지가 보이고 좌측 페이지 그룹으로 이동할 수 있는 버턴이 나타나야 한다.
- [ ] TDD로 구현해야 합니다.
  - 어떻게 해야될지 고민 중 입니다.....

---------

- handlebar 의 helper 기능을 좀 더 써보고 싶었는데, 의도대로 되지 않아 model 에 값을 넣는 방식으로 페이지 구분을 구현하였습니다.
- 좀 더 개선할 것으로는 모든 request 를 api 로 만들고 ajax or fetch 의 형태로 만드는 것인데.. 한번 하다 실패한 후 손을 못대고 있습니다 ㅠ

2020-03-18 23:32 UTC, wheejuni requested changes
수고 많으셨어요. 
코멘트 한번씩만 참고해주셔요.

2020-03-18 23:32 UTC, wheejuni commented on src/main/java/com/codessquad/qna/answer/AnswerController.java
> +    Question question = getQuestion(questionRepository, questionId);
새 메소드명이 훨씬 자연스럽네요! ㅎㅎㅎ

2020-03-18 23:32 UTC, wheejuni commented on src/main/java/com/codessquad/qna/commons/CommonController.java
> +    Map<Integer, String> pageCountMap = new LinkedHashMap<>();
혹시 `LinkedHashMap` 을 사용한 이유를 알 수 있을까요?

2020-03-18 23:32 UTC, wheejuni commented on src/main/java/com/codessquad/qna/commons/CommonController.java
> +    int pageCountInteger = Integer.parseInt(pageCount);
Argument로 받는 변수의 이름을 `pageCountRequest` 정도로 두고, 이 변수의 접미사는 떼는 것이 더 자연스러울 것 같아요.

2020-03-18 23:32 UTC, wheejuni commented on src/main/java/com/codessquad/qna/commons/CommonController.java
> +    Pageable firstPageWithTwoElements = PageRequest.of(0, 15, Sort.by("lastModifiedDateTime").descending());
15라는 숫자는 일종의 제한값으로 보여지는데,
그렇다면 클래스 상단에서 상수값으로 관리해주세요.

2020-03-18 23:32 UTC, wheejuni commented on src/main/java/com/codessquad/qna/commons/CommonUtils.java
> +  @Autowired
여기서 `@Autowired` 사용하면 잘 작동하던가요?

2020-03-18 23:32 UTC, wheejuni commented on src/main/java/com/codessquad/qna/commons/CommonUtils.java
> +    User user = optionalUser.orElseThrow(() -> new UserException(CustomMessage.USER_NOT_EXIST));
여기서 바로 `return`해 주어도 됩니다.

2020-03-18 23:32 UTC, wheejuni commented on src/main/java/com/codessquad/qna/commons/CommonUtils.java
>  public class CommonUtils {
지난번에도 한 번 말했던 것 같은데 특정 도메인 객체를 가공하고 조회하는 로직이 담긴 이상 이 클래스는 `Common`한 건 아닙니다. 

클래스의 이름을 바꾸던지, 그런 로직들을 분리시키던지 해 주세요.

2020-03-18 23:32 UTC, wheejuni commented on src/main/java/com/codessquad/qna/commons/Result.java
> +  public Result(Object valid, Object errorMessage, Object object) {
`Object` 타입 파라미터를 받는 이유가 뭔가요?

2020-03-18 23:32 UTC, wheejuni commented on src/main/java/com/codessquad/qna/errors/UserException.java
> +  public UserException(String CustomMessage) {
파라미터 이름은 소문자로 시작합시다^^

2020-03-18 23:32 UTC, wheejuni commented on src/main/java/com/codessquad/qna/question/Question.java
> +    System.out.println("### checkAnswersWriter()");
콘솔 라이팅 하지 맙시다. 
로거를 사용해주세요.

2020-03-18 23:32 UTC, wheejuni commented on src/main/java/com/codessquad/qna/question/Question.java
> +    return this.answers.stream().allMatch(answer -> answer.getUser() == this.user);
객체를 `==`으로 비교하는 것은 어떤 경우에도 피해주세요. 명시적으로 동일성을 비교해야 하는 상황이 아니면요. 


https://joont.tistory.com/m/143

2020-03-18 23:32 UTC, wheejuni commented on src/main/java/com/codessquad/qna/user/ApiUserController.java
> +    log.debug("### " + user.toString());
로거 안에서 `{}` 사용해서 interpolation 해 주세요. 
`log.debug(“hello {}”, “Dan”)` 이런 식으로요^^

2020-03-18 23:32 UTC, wheejuni commented on src/main/java/com/codessquad/qna/user/ApiUserController.java
> +    log.debug("### " + user.toString());
상단 코멘트 참고해 주시고요

2020-03-18 23:32 UTC, wheejuni commented on src/main/java/com/codessquad/qna/user/ApiUserController.java
> +//2020-03-12 02:31:27:526 DEBUG [http-nio-8080-exec-3] o.s.c.l.LogFormatUtils: POST "/users", parameters={masked}
불필요한 주석 다 삭제해주세요. 
코드에 이런 불필요한 주석이 묻어있는 건 그 자체로 생산성을 떨어트리기도 하고요,
현업에 나가셔도 이렇게 하시면 아마 혼날 겁니다. 
로그 내용을 기록해두길 원하면 별도의 메모 앱을 사용하시기를 권합니다.

2020-03-18 23:32 UTC, wheejuni commented on src/main/java/com/codessquad/qna/user/UserRepository.java
> +  @Override
`findAll()` 이 이미 `CrudRepository` 에서 제공되는데 굳이 또 작성한 이유가 있나요?

2020-03-18 23:32 UTC, wheejuni commented on src/main/resources/static/js/scripts.js
> +  var queryString = $("form[name=answer]").serialize();
`.serialize()` 를 사용한 이유를 알 수 있을까요?

2020-03-19 05:03 UTC, Hyune-c commented on src/main/java/com/codessquad/qna/commons/CommonController.java
> +    Map<Integer, String> pageCountMap = new LinkedHashMap<>();
pageCountMap 은 글 하단에 최대 6개의 페이지 이동 버튼을 만들어주는 Map 입니다. 
따라서 페이지의 순서가 보장되면 더 좋을 것이라고 생각했기에 사용했었는데..

다시 생각해보니까 어짜피 HashMap 이라서 O(1) 로 검색할 수 있기에 의미는 없었던 것 같습니다.

2020-03-19 05:04 UTC, Hyune-c commented on src/main/java/com/codessquad/qna/commons/CommonController.java
> +    int pageCountInteger = Integer.parseInt(pageCount);
`int pageCount = Integer.parseInt(pageCountRequest);`
로 수정해보겠습니다.

2020-03-19 13:23 UTC, Hyune-c commented on src/main/java/com/codessquad/qna/user/UserRepository.java
> +  @Override
return 형이 List<> 가 아니라 Iterable 인가로 봤던거 같은데.. javadoc 보니까 List<> 가 맞네요.. 수정하겠습니다. ㅠ

2020-03-19 13:24 UTC, Hyune-c commented on src/main/resources/static/js/scripts.js
> +  var queryString = $("form[name=answer]").serialize();
json 형태를 사용하기 위함이라고 예시에서 본거 같은데 정확한 의도를 가지고 사용하지는 못한듯 합니다. ㅠ

2020-03-19 13:25 UTC, Hyune-c commented on src/main/java/com/codessquad/qna/user/ApiUserController.java
> +    log.debug("### " + user.toString());
넵. 이번에 배웠습니다. 앞으로는 그렇게 하겠습니다.

2020-03-19 13:26 UTC, Hyune-c commented on src/main/java/com/codessquad/qna/commons/CommonUtils.java
>  public class CommonUtils {
클래스 이름을 변경하도록 해보겠습니다.

2020-03-19 13:26 UTC, Hyune-c commented on src/main/java/com/codessquad/qna/commons/Result.java
> +  public Result(Object valid, Object errorMessage, Object object) {
어떤 형태가 들어올지 모른다고 예상해서 넣었는데.. 짜다보니 특정시킬 수 있을 거 같습니다. 개선해보겠습니다.

2020-03-20 06:14 UTC, honux77 commented on src/main/java/com/codessquad/qna/commons/CommonController.java
> +    Map<Integer, String> pageCountMap = new LinkedHashMap<>();
순서 보장은 treeMap 같은 건 어때요? SortedMap 중에 treeMap이 종종 씌이는 것 같아요.

2020-03-20 06:15 UTC, honux77 commented on src/main/java/com/codessquad/qna/commons/CommonUtils.java
> +  @Autowired
ㅋㅋㅋ 저도 궁금하네요. 
빈이 아닌 경우에는 주입받으면 안 되는데...

2020-03-20 06:16 UTC, merged

2020-03-20 06:16 UTC, honux77 commented
긴 시간 동안 수고 많이 했어요!

2020-03-20 06:49 UTC, Hyune-c commented on src/main/java/com/codessquad/qna/commons/CommonUtils.java
> +  @Autowired
엇 이거 되던데요..

사실 좀 이상한 구현이긴 합니다.

Util 클래스 임에도 static 메소드가 아니기 때문이긴 하데. 저것을 만들 당시에는 개선 방법을 찾지못해 저렇게 억지로 구현하였습니다.

2020-03-20 07:41 UTC, wheejuni commented on src/main/java/com/codessquad/qna/commons/CommonUtils.java
> +  @Autowired
Util 클래스의 역할을 줄여보세요.

2020-03-20 07:45 UTC, Hyune-c commented on src/main/java/com/codessquad/qna/commons/CommonController.java
> +    Map<Integer, String> pageCountMap = new LinkedHashMap<>();
TreeMap 은 아직 한번도 써보지 못했는데.. 공부해보겠습니다!