[XP/LYNN] Step5
code-squad/java-qna pull request #226
Opened 2020-03-20 06:21 UTC by beemiel

### [HEROKU](https://lynn-java-qna.herokuapp.com/)

### step5
- AJAX로 답변 추가
- AJAX로 답변 삭제
- 답변 삭제 기능 버그 해결

[XP 질문]
이 코드에는 나와있지 않은데 제가 댓글을 다는 기능을 ajax로 구현할 때 onsucess 함수가 실행될 때 데이터가 잘 넘어오는지 console.log(data) 를 찍어보았는데 린이나 다른 분들은 json 데이터가 잘 넘어오는데 저는 Object object 로 찍힙니다. 근데 다른 문제는 없어요. 왜 Object 로 반환되는지 궁금합니다.

2020-03-20 11:14 UTC, wheejuni requested changes
수고 많으셨어요.
XP의 질문에 답변 드릴게요. 

아마 다른 분들은 `onsuccess(data)` 함수 안에서 `JSON.stringify()` 같은 것을 쓴 건 아닐까요. 
한번 `JSON.stringify()` 에 넣고 돌려보세요. 뭔가 변화가 생길수도....

2020-03-20 11:14 UTC, wheejuni commented on src/main/java/com/codessquad/qna/controller/ApiAnswerController.java
> +        //어떻게 업데이트 되는 건지
ㅋㅋㅋ 저도 신기하네요 이게 무슨일이죠??!!

2020-03-20 11:14 UTC, wheejuni commented on src/main/java/com/codessquad/qna/controller/ApiAnswerController.java
> +        //어떻게 업데이트 되는 건지
그냥 슬쩍 읽어보세요. https://kingbbode.tistory.com/27

2020-03-20 11:14 UTC, wheejuni commented on src/main/java/com/codessquad/qna/controller/ApiAnswerController.java
> +        question.addCount();
흐음. 양방향 1:N 관계를 가졌으면 굳이 이런 메소드는 필요없었을 것 같기도 하구요. 
아래 엔티티 클래스에서 더 들여다보죠.

2020-03-20 11:14 UTC, wheejuni commented on src/main/java/com/codessquad/qna/controller/ApiAnswerController.java
> +            return Result.fail("zz");
ㅋㅋ

2020-03-20 11:14 UTC, wheejuni commented on src/main/java/com/codessquad/qna/controller/ApiUserController.java
> +        return userRepository.findById(id).orElseThrow(EntityNotFoundException::new);
method reference 쓴 것 좋네요.

2020-03-20 11:14 UTC, wheejuni commented on src/main/java/com/codessquad/qna/domain/AbstractEntity.java
> +    @JsonProperty
헉. `@JsonIgnore` 가 아니고 `@JsonProperty` 인가요.
JSON 필드의 이름을 바꾸거나 하려는 목적이 아니면 굳이 이렇게 달아줄 필요는 없습니다.

2020-03-20 11:14 UTC, wheejuni commented on src/main/java/com/codessquad/qna/domain/AbstractEntity.java
> +    }
반복되는 날짜 양식을 클래스 상단에서 `static` 으로 관리해주면 어떨까요.

2020-03-20 11:14 UTC, wheejuni commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    private Integer countOfAnswer = 0;
흠... `answers` 필드가 있다면, `answers.size()` 정도로 해결할 수 있지 않았을까요? 
그렇게 했더니 잘 안됐나요? 왜 안됐을까요?

2020-03-20 11:14 UTC, wheejuni commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    public Integer getCountOfAnswer() {
아, JSON에서 값을 내려주기 위해서 이런 방법을 혹시 쓴건가요. 
사실 Jackson은 멍청해서 메소드 이름이 `.get` 으로 시작하면 다 JSON 필드를 만들어 줘요. 
`countOfAnswer` 라는 필드가 없었어도 그냥 이 메소드 안에서 `answers.size()` 를 호출했으면 해결할 수 있었을 거에요.

2020-03-20 11:14 UTC, wheejuni commented on src/main/java/com/codessquad/qna/domain/User.java
> +        return getId().equals(inputId);
헙. 굳이 이렇게 바꾼 이유가 뭘까요?

2020-03-22 13:50 UTC, honux77 commented
주석 ㅎㅎ 두분다 즐겁게 코딩하세요! 화이팅!

2020-03-22 13:50 UTC, merged

2020-03-22 14:47 UTC, beemiel commented on src/main/java/com/codessquad/qna/domain/AbstractEntity.java
> +    @JsonProperty
@JsonProperty를 다른 Entitiy에서도 많이 썼는데 이 어노테이션을 사용한 이유는 getter가 없으면 이 어노테이션을 사용해서 json으로 만들 수 있다고 해서 붙였습니다. @JsonProperty 의 사용법이 틀렸나요? 지금은 id의 getter가 있으니까 없어도 되긴 하네요.
@JsonIgnore을 하지 않은건 답변을 삭제할 때 id값이 필요해서 하지 않았습니다.

2020-03-22 14:47 UTC, beemiel commented on src/main/java/com/codessquad/qna/domain/Question.java
> +    private Integer countOfAnswer = 0;
양방향 매핑을 제대로 이해하지 못했었네요...

2020-03-22 14:48 UTC, beemiel commented on src/main/java/com/codessquad/qna/domain/User.java
> +        return getId().equals(inputId);
id 가 모든 entitiy에 중복이 돼서 AbstractEntity라는 상위 클래스를 만들고 다른 entity들이 이 클래스를 상속받도록 바꿨더니 id가 private이어서 하위 클래스에서 id를 사용하려고 getter를 써서 바꿨는데 getter는 최대한 지양해야 하나요?  protected로 하는게 나을까요? 아니면 해당 메소드를 User에서만 사용해도 상위 클래스의 메소드로 만드는게 낫나요?