[Henry] step6
code-squad/java-qna pull request #229
Opened 2020-03-22 16:49 UTC by wooody92

## STEP6

- https://wooody92.herokuapp.com

> 함께한 팀원 : Jack
> 페어프로그래밍 방식 : Ground rule 논의 -> Step6의 페이지 기능 구현을 위해 학습 후 아이디어 공유 -> 함께 코드 작성 -> 세부적인 기능을 각자 수정 후 P.R

### 0. 구현 기능

- 동적으로 구동하는 페이지 나누기 기능 구현했습니다.
- 페이지를 각 양 끝으로 이동하면, 이전 혹은 다음 버튼을 보이지않게 제거하여 예상치못한 버그차단 했습니다.
- PageController와 PageUtils 클래스를 목적성에 맞게 분리했습니다.
- ApiAnswerController(json api 처리) - AnswerController(view page 처리) 분리

### 1. 회고

- PageUtils 클래스를 만들어서 페이지 컨트롤러에서 import static 선언하여 사용하려고 했는데 하다보니 여러 문제가 생겼습니다. 주로 QuestionRepository를 가져다 쓰면서 발생한 문제였는데 그래서 궁금한점이 있습니다.

  1. @Autowired QuestionRepository는 static하게 사용하는 것은 바람직하지 않나요?

  2. 아래 삽질했던 링크처럼 클래스 생성자에서 QuestionRepository를 사용하고 싶은데, 생성자 수행전에 @Autowired 시키는 방법은 없을까요?

  3. 실제 작성한 코드에서는 빈을 제거하고, QuestionRepository를 매개변수로 하는 메서드들을 만들어 사용했는데 괜찮을까요?

     https://github.com/wooody92/notes/blob/master/spring/삽질노트/0319%20auto-wired%20before%20class%20constructor.md

2020-03-23 23:37 UTC, wheejuni requested changes
수고 많으셨습니다. 
다음 프로젝트 준비로 바쁘시겠지만 코멘트 한 번씩만 읽어주세요.

2020-03-23 23:37 UTC, wheejuni commented on README.md
> +  1. @Autowired QuestionRepository는 static하게 사용하는 것은 바람직하지 않나요?
네. 그렇게 하면 주입되지 않아요. 
바람직하지 않은 것이 아니라 아예 작동하지 않을 거에요. 
`static`의 작동원리에 대해 학습해보면 그 이유는 알 수 있을거에요.

2020-03-23 23:37 UTC, wheejuni commented on README.md
> +  2. 아래 삽질했던 링크처럼 클래스 생성자에서 QuestionRepository를 사용하고 싶은데, 생성자 수행전에 @Autowired 시키는 방법은 없을까요?
네! 없습니다^^
생성자에서 왜 주입받은 컴포넌트가 필요했을지 생각해보고, 그 이유를 찾아서 없애는게 낫습니다.

2020-03-23 23:37 UTC, wheejuni commented on README.md
> +  3. 실제 작성한 코드에서는 빈을 제거하고, QuestionRepository를 매개변수로 하는 메서드들을 만들어 사용했는데 괜찮을까요?
_안 괜찮습니다. _
빈은 컴포넌트의 필드에만 존재하는 것이 가장 바람직해요.

2020-03-23 23:37 UTC, wheejuni commented on src/main/java/com/codessquad/qna/AnswerController.java
> +import static com.codessquad.qna.HttpSessionUtils.isLogin;
Static import가 단순 코드량을 줄여주므로 좋아 보일수도 있지만,
지금같은 상황에서는 명시적으로 어떤 유틸의 메소드를 호출한건지 문맥상 알려줘야 할 필요도 있어보입니다. 
(유틸 클래스의 클래스명 작명이 잘 되었다는 전제 하에)스태틱 임포트를 사용하실 때는 이 점 한번만 다시 생각해주세요.

2020-03-23 23:37 UTC, wheejuni commented on src/main/java/com/codessquad/qna/PageUtils.java
> +    private int firstPage;
Util 클래스에 인스턴스 변수가 이렇게 많으면 안됩니다.

2020-03-23 23:37 UTC, wheejuni commented on src/main/java/com/codessquad/qna/PageUtils.java
> +    public void initPage(QuestionRepository questionRepository) {
`Pageable` 객체를 파라미터로 받는 방향으로 아래 메소드까지 전부 리팩토링해주세요. 

그렇게 하면 굳이 레포지토리를 받지 않아도 될 것 같네요. 그리고 그렇게 구현하는 편이 기능적으로도 더 효율적일 것으로 보여집니다. 

나중에 유저로 하여금 한 페이지에 20개씩 보게 한다던지, 이런 유저의 세팅에 따라 페이징 요청이 바뀌어야 하는 설계가 들어온다면 어떻게 할 건가요?

2020-03-23 23:37 UTC, wheejuni commented on src/main/java/com/codessquad/qna/PageUtils.java
> +    public String preButton() {
View에 종속되는 피쳐가 유틸 클래스까지 침투하는 것은 바람직하지 않습니다. 
상기한 코멘트와 마찬가지로 뒤/앞 버튼 스펙이 변경되면 어떻게 되나요. 
유틸 클래스에는 통일된 연산 결과가 보장되는 로직만 담고 뷰의 일은 뷰에서 처리합시다.

2021-02-26 07:26 UTC, merged

2021-02-26 07:26 UTC, honux77 commented
ㅋㅋㅋ 엄청 늦었지만 머지 완료! 죄송합니다.